/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as QuestionsIndexRouteImport } from './routes/questions.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as ContentIndexRouteImport } from './routes/content.index'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherTeamRouteImport } from './routes/teacher.team'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherSessionsRouteImport } from './routes/teacher.sessions'
import { Route as TeacherRewardsRouteImport } from './routes/teacher.rewards'
import { Route as TeacherRevenueRouteImport } from './routes/teacher.revenue'
import { Route as TeacherQuizzesRouteImport } from './routes/teacher.quizzes'
import { Route as TeacherQuestionsRouteImport } from './routes/teacher.questions'
import { Route as TeacherLessonsRouteImport } from './routes/teacher.lessons'
import { Route as TeacherGeneratorRouteImport } from './routes/teacher.generator'
import { Route as TeacherCoursesRouteImport } from './routes/teacher.courses'
import { Route as TeacherChatRouteImport } from './routes/teacher.chat'
import { Route as TeacherChaptersRouteImport } from './routes/teacher.chapters'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as TeacherAnalyticsRouteImport } from './routes/teacher.analytics'
import { Route as SuperSystemRouteImport } from './routes/super.system'
import { Route as SuperAuditRouteImport } from './routes/super.audit'
import { Route as SuperAnalyticsRouteImport } from './routes/super.analytics'
import { Route as SuperAccessMatrixRouteImport } from './routes/super.access-matrix'
import { Route as StudentWrongQuestionsRouteImport } from './routes/student.wrong-questions'
import { Route as StudentWalletRouteImport } from './routes/student.wallet'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentNotesRouteImport } from './routes/student.notes'
import { Route as StudentLessonRouteImport } from './routes/student.lesson'
import { Route as StudentLeaderboardRouteImport } from './routes/student.leaderboard'
import { Route as StudentCourseDetailsRouteImport } from './routes/student.course-details'
import { Route as StudentCertificatesRouteImport } from './routes/student.certificates'
import { Route as QuizStartRouteImport } from './routes/quiz.start'
import { Route as QuestionsWrongRouteImport } from './routes/questions.wrong'
import { Route as ParentProgressRouteImport } from './routes/parent.progress'
import { Route as ParentMessagesRouteImport } from './routes/parent.messages'
import { Route as ParentHomeworkRouteImport } from './routes/parent.homework'
import { Route as ParentAttendanceRouteImport } from './routes/parent.attendance'
import { Route as FinanceSubscriptionsRouteImport } from './routes/finance.subscriptions'
import { Route as FinanceRevenueRouteImport } from './routes/finance.revenue'
import { Route as FinancePaymentsRouteImport } from './routes/finance.payments'
import { Route as FinanceInvoicesRouteImport } from './routes/finance.invoices'
import { Route as FinanceCouponsRouteImport } from './routes/finance.coupons'
import { Route as DeveloperVersionsRouteImport } from './routes/developer.versions'
import { Route as DeveloperFrontendRouteImport } from './routes/developer.frontend'
import { Route as DeveloperFeatureFlagsRouteImport } from './routes/developer.feature-flags'
import { Route as DeveloperErrorLogsRouteImport } from './routes/developer.error-logs'
import { Route as DeveloperDeploymentsRouteImport } from './routes/developer.deployments'
import { Route as DeveloperBackendRouteImport } from './routes/developer.backend'
import { Route as DeveloperApiHealthRouteImport } from './routes/developer.api-health'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as ContentQuestionReviewRouteImport } from './routes/content.question-review'
import { Route as ContentMediaRouteImport } from './routes/content.media'
import { Route as ContentLessonReviewRouteImport } from './routes/content.lesson-review'
import { Route as ContentImportRouteImport } from './routes/content.import'
import { Route as ContentCurriculumRouteImport } from './routes/content.curriculum'
import { Route as AssistantStudyPlanRouteImport } from './routes/assistant.study-plan'
import { Route as AssistantSolveRouteImport } from './routes/assistant.solve'
import { Route as AssistantExplainRouteImport } from './routes/assistant.explain'
import { Route as AssistantAnalyzeRouteImport } from './routes/assistant.analyze'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as StudentCoursesIndexRouteImport } from './routes/student.courses.index'
import { Route as TeacherQuestionsCreateRouteImport } from './routes/teacher.questions.create'
import { Route as StudentCoursesCourseIdRouteImport } from './routes/student.courses.$courseId'
import { Route as StudentCertificatesCertificateIdRouteImport } from './routes/student.certificates.$certificateId'
import { Route as StudentCoursesCourseIdIndexRouteImport } from './routes/student.courses.$courseId.index'
import { Route as StudentCoursesCourseIdSessionRouteImport } from './routes/student.courses.$courseId.session'
import { Route as StudentCoursesCourseIdResourcesRouteImport } from './routes/student.courses.$courseId.resources'
import { Route as StudentCoursesCourseIdEnrollRouteImport } from './routes/student.courses.$courseId.enroll'
import { Route as StudentCoursesCourseIdContinueRouteImport } from './routes/student.courses.$courseId.continue'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/super/',
  path: '/super/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTeamRoute = TeacherTeamRouteImport.update({
  id: '/teacher/team',
  path: '/teacher/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/teacher/students',
  path: '/teacher/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSessionsRoute = TeacherSessionsRouteImport.update({
  id: '/teacher/sessions',
  path: '/teacher/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRewardsRoute = TeacherRewardsRouteImport.update({
  id: '/teacher/rewards',
  path: '/teacher/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRevenueRoute = TeacherRevenueRouteImport.update({
  id: '/teacher/revenue',
  path: '/teacher/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherQuizzesRoute = TeacherQuizzesRouteImport.update({
  id: '/teacher/quizzes',
  path: '/teacher/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherQuestionsRoute = TeacherQuestionsRouteImport.update({
  id: '/teacher/questions',
  path: '/teacher/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLessonsRoute = TeacherLessonsRouteImport.update({
  id: '/teacher/lessons',
  path: '/teacher/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherGeneratorRoute = TeacherGeneratorRouteImport.update({
  id: '/teacher/generator',
  path: '/teacher/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({
  id: '/teacher/courses',
  path: '/teacher/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherChatRoute = TeacherChatRouteImport.update({
  id: '/teacher/chat',
  path: '/teacher/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherChaptersRoute = TeacherChaptersRouteImport.update({
  id: '/teacher/chapters',
  path: '/teacher/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/teacher/assignments',
  path: '/teacher/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAnalyticsRoute = TeacherAnalyticsRouteImport.update({
  id: '/teacher/analytics',
  path: '/teacher/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperSystemRoute = SuperSystemRouteImport.update({
  id: '/super/system',
  path: '/super/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAuditRoute = SuperAuditRouteImport.update({
  id: '/super/audit',
  path: '/super/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAnalyticsRoute = SuperAnalyticsRouteImport.update({
  id: '/super/analytics',
  path: '/super/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAccessMatrixRoute = SuperAccessMatrixRouteImport.update({
  id: '/super/access-matrix',
  path: '/super/access-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWrongQuestionsRoute = StudentWrongQuestionsRouteImport.update({
  id: '/wrong-questions',
  path: '/wrong-questions',
  getParentRoute: () => StudentRoute,
} as any)
const StudentWalletRoute = StudentWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotesRoute = StudentNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLessonRoute = StudentLessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLeaderboardRoute = StudentLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCourseDetailsRoute = StudentCourseDetailsRouteImport.update({
  id: '/course-details',
  path: '/course-details',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRoute,
} as any)
const QuizStartRoute = QuizStartRouteImport.update({
  id: '/quiz/start',
  path: '/quiz/start',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsWrongRoute = QuestionsWrongRouteImport.update({
  id: '/questions/wrong',
  path: '/questions/wrong',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentProgressRoute = ParentProgressRouteImport.update({
  id: '/parent/progress',
  path: '/parent/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentMessagesRoute = ParentMessagesRouteImport.update({
  id: '/parent/messages',
  path: '/parent/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentHomeworkRoute = ParentHomeworkRouteImport.update({
  id: '/parent/homework',
  path: '/parent/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentAttendanceRoute = ParentAttendanceRouteImport.update({
  id: '/parent/attendance',
  path: '/parent/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceSubscriptionsRoute = FinanceSubscriptionsRouteImport.update({
  id: '/finance/subscriptions',
  path: '/finance/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRevenueRoute = FinanceRevenueRouteImport.update({
  id: '/finance/revenue',
  path: '/finance/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceInvoicesRoute = FinanceInvoicesRouteImport.update({
  id: '/finance/invoices',
  path: '/finance/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCouponsRoute = FinanceCouponsRouteImport.update({
  id: '/finance/coupons',
  path: '/finance/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperVersionsRoute = DeveloperVersionsRouteImport.update({
  id: '/developer/versions',
  path: '/developer/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperFrontendRoute = DeveloperFrontendRouteImport.update({
  id: '/developer/frontend',
  path: '/developer/frontend',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperFeatureFlagsRoute = DeveloperFeatureFlagsRouteImport.update({
  id: '/developer/feature-flags',
  path: '/developer/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperErrorLogsRoute = DeveloperErrorLogsRouteImport.update({
  id: '/developer/error-logs',
  path: '/developer/error-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperDeploymentsRoute = DeveloperDeploymentsRouteImport.update({
  id: '/developer/deployments',
  path: '/developer/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperBackendRoute = DeveloperBackendRouteImport.update({
  id: '/developer/backend',
  path: '/developer/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperApiHealthRoute = DeveloperApiHealthRouteImport.update({
  id: '/developer/api-health',
  path: '/developer/api-health',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const ContentQuestionReviewRoute = ContentQuestionReviewRouteImport.update({
  id: '/content/question-review',
  path: '/content/question-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentMediaRoute = ContentMediaRouteImport.update({
  id: '/content/media',
  path: '/content/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentLessonReviewRoute = ContentLessonReviewRouteImport.update({
  id: '/content/lesson-review',
  path: '/content/lesson-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentImportRoute = ContentImportRouteImport.update({
  id: '/content/import',
  path: '/content/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCurriculumRoute = ContentCurriculumRouteImport.update({
  id: '/content/curriculum',
  path: '/content/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantStudyPlanRoute = AssistantStudyPlanRouteImport.update({
  id: '/assistant/study-plan',
  path: '/assistant/study-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantSolveRoute = AssistantSolveRouteImport.update({
  id: '/assistant/solve',
  path: '/assistant/solve',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantExplainRoute = AssistantExplainRouteImport.update({
  id: '/assistant/explain',
  path: '/assistant/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantAnalyzeRoute = AssistantAnalyzeRouteImport.update({
  id: '/assistant/analyze',
  path: '/assistant/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesIndexRoute = StudentCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherQuestionsCreateRoute = TeacherQuestionsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TeacherQuestionsRoute,
} as any)
const StudentCoursesCourseIdRoute = StudentCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificatesCertificateIdRoute =
  StudentCertificatesCertificateIdRouteImport.update({
    id: '/$certificateId',
    path: '/$certificateId',
    getParentRoute: () => StudentCertificatesRoute,
  } as any)
const StudentCoursesCourseIdIndexRoute =
  StudentCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudentCoursesCourseIdRoute,
  } as any)
const StudentCoursesCourseIdSessionRoute =
  StudentCoursesCourseIdSessionRouteImport.update({
    id: '/session',
    path: '/session',
    getParentRoute: () => StudentCoursesCourseIdRoute,
  } as any)
const StudentCoursesCourseIdResourcesRoute =
  StudentCoursesCourseIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => StudentCoursesCourseIdRoute,
  } as any)
const StudentCoursesCourseIdEnrollRoute =
  StudentCoursesCourseIdEnrollRouteImport.update({
    id: '/enroll',
    path: '/enroll',
    getParentRoute: () => StudentCoursesCourseIdRoute,
  } as any)
const StudentCoursesCourseIdContinueRoute =
  StudentCoursesCourseIdContinueRouteImport.update({
    id: '/continue',
    path: '/continue',
    getParentRoute: () => StudentCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/banners': typeof AdminBannersRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/assistant/analyze': typeof AssistantAnalyzeRoute
  '/assistant/explain': typeof AssistantExplainRoute
  '/assistant/solve': typeof AssistantSolveRoute
  '/assistant/study-plan': typeof AssistantStudyPlanRoute
  '/content/curriculum': typeof ContentCurriculumRoute
  '/content/import': typeof ContentImportRoute
  '/content/lesson-review': typeof ContentLessonReviewRoute
  '/content/media': typeof ContentMediaRoute
  '/content/question-review': typeof ContentQuestionReviewRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/developer/api-health': typeof DeveloperApiHealthRoute
  '/developer/backend': typeof DeveloperBackendRoute
  '/developer/deployments': typeof DeveloperDeploymentsRoute
  '/developer/error-logs': typeof DeveloperErrorLogsRoute
  '/developer/feature-flags': typeof DeveloperFeatureFlagsRoute
  '/developer/frontend': typeof DeveloperFrontendRoute
  '/developer/versions': typeof DeveloperVersionsRoute
  '/finance/coupons': typeof FinanceCouponsRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/revenue': typeof FinanceRevenueRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/homework': typeof ParentHomeworkRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/progress': typeof ParentProgressRoute
  '/questions/wrong': typeof QuestionsWrongRoute
  '/quiz/start': typeof QuizStartRoute
  '/student/certificates': typeof StudentCertificatesRouteWithChildren
  '/student/course-details': typeof StudentCourseDetailsRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/lesson': typeof StudentLessonRoute
  '/student/notes': typeof StudentNotesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/wallet': typeof StudentWalletRoute
  '/student/wrong-questions': typeof StudentWrongQuestionsRoute
  '/super/access-matrix': typeof SuperAccessMatrixRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/audit': typeof SuperAuditRoute
  '/super/system': typeof SuperSystemRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/chapters': typeof TeacherChaptersRoute
  '/teacher/chat': typeof TeacherChatRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/generator': typeof TeacherGeneratorRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/questions': typeof TeacherQuestionsRouteWithChildren
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/teacher/revenue': typeof TeacherRevenueRoute
  '/teacher/rewards': typeof TeacherRewardsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/team': typeof TeacherTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/assistant/': typeof AssistantIndexRoute
  '/content/': typeof ContentIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/student/': typeof StudentIndexRoute
  '/super/': typeof SuperIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/certificates/$certificateId': typeof StudentCertificatesCertificateIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRouteWithChildren
  '/teacher/questions/create': typeof TeacherQuestionsCreateRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/student/courses/$courseId/continue': typeof StudentCoursesCourseIdContinueRoute
  '/student/courses/$courseId/enroll': typeof StudentCoursesCourseIdEnrollRoute
  '/student/courses/$courseId/resources': typeof StudentCoursesCourseIdResourcesRoute
  '/student/courses/$courseId/session': typeof StudentCoursesCourseIdSessionRoute
  '/student/courses/$courseId/': typeof StudentCoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/assistant/analyze': typeof AssistantAnalyzeRoute
  '/assistant/explain': typeof AssistantExplainRoute
  '/assistant/solve': typeof AssistantSolveRoute
  '/assistant/study-plan': typeof AssistantStudyPlanRoute
  '/content/curriculum': typeof ContentCurriculumRoute
  '/content/import': typeof ContentImportRoute
  '/content/lesson-review': typeof ContentLessonReviewRoute
  '/content/media': typeof ContentMediaRoute
  '/content/question-review': typeof ContentQuestionReviewRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/developer/api-health': typeof DeveloperApiHealthRoute
  '/developer/backend': typeof DeveloperBackendRoute
  '/developer/deployments': typeof DeveloperDeploymentsRoute
  '/developer/error-logs': typeof DeveloperErrorLogsRoute
  '/developer/feature-flags': typeof DeveloperFeatureFlagsRoute
  '/developer/frontend': typeof DeveloperFrontendRoute
  '/developer/versions': typeof DeveloperVersionsRoute
  '/finance/coupons': typeof FinanceCouponsRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/revenue': typeof FinanceRevenueRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/homework': typeof ParentHomeworkRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/progress': typeof ParentProgressRoute
  '/questions/wrong': typeof QuestionsWrongRoute
  '/quiz/start': typeof QuizStartRoute
  '/student/certificates': typeof StudentCertificatesRouteWithChildren
  '/student/course-details': typeof StudentCourseDetailsRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/lesson': typeof StudentLessonRoute
  '/student/notes': typeof StudentNotesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/wallet': typeof StudentWalletRoute
  '/student/wrong-questions': typeof StudentWrongQuestionsRoute
  '/super/access-matrix': typeof SuperAccessMatrixRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/audit': typeof SuperAuditRoute
  '/super/system': typeof SuperSystemRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/chapters': typeof TeacherChaptersRoute
  '/teacher/chat': typeof TeacherChatRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/generator': typeof TeacherGeneratorRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/questions': typeof TeacherQuestionsRouteWithChildren
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/teacher/revenue': typeof TeacherRevenueRoute
  '/teacher/rewards': typeof TeacherRewardsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/team': typeof TeacherTeamRoute
  '/admin': typeof AdminIndexRoute
  '/assistant': typeof AssistantIndexRoute
  '/content': typeof ContentIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/parent': typeof ParentIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/student': typeof StudentIndexRoute
  '/super': typeof SuperIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/certificates/$certificateId': typeof StudentCertificatesCertificateIdRoute
  '/teacher/questions/create': typeof TeacherQuestionsCreateRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/student/courses/$courseId/continue': typeof StudentCoursesCourseIdContinueRoute
  '/student/courses/$courseId/enroll': typeof StudentCoursesCourseIdEnrollRoute
  '/student/courses/$courseId/resources': typeof StudentCoursesCourseIdResourcesRoute
  '/student/courses/$courseId/session': typeof StudentCoursesCourseIdSessionRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/banners': typeof AdminBannersRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/assistant/analyze': typeof AssistantAnalyzeRoute
  '/assistant/explain': typeof AssistantExplainRoute
  '/assistant/solve': typeof AssistantSolveRoute
  '/assistant/study-plan': typeof AssistantStudyPlanRoute
  '/content/curriculum': typeof ContentCurriculumRoute
  '/content/import': typeof ContentImportRoute
  '/content/lesson-review': typeof ContentLessonReviewRoute
  '/content/media': typeof ContentMediaRoute
  '/content/question-review': typeof ContentQuestionReviewRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/developer/api-health': typeof DeveloperApiHealthRoute
  '/developer/backend': typeof DeveloperBackendRoute
  '/developer/deployments': typeof DeveloperDeploymentsRoute
  '/developer/error-logs': typeof DeveloperErrorLogsRoute
  '/developer/feature-flags': typeof DeveloperFeatureFlagsRoute
  '/developer/frontend': typeof DeveloperFrontendRoute
  '/developer/versions': typeof DeveloperVersionsRoute
  '/finance/coupons': typeof FinanceCouponsRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/revenue': typeof FinanceRevenueRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/homework': typeof ParentHomeworkRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/progress': typeof ParentProgressRoute
  '/questions/wrong': typeof QuestionsWrongRoute
  '/quiz/start': typeof QuizStartRoute
  '/student/certificates': typeof StudentCertificatesRouteWithChildren
  '/student/course-details': typeof StudentCourseDetailsRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/lesson': typeof StudentLessonRoute
  '/student/notes': typeof StudentNotesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/wallet': typeof StudentWalletRoute
  '/student/wrong-questions': typeof StudentWrongQuestionsRoute
  '/super/access-matrix': typeof SuperAccessMatrixRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/audit': typeof SuperAuditRoute
  '/super/system': typeof SuperSystemRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/chapters': typeof TeacherChaptersRoute
  '/teacher/chat': typeof TeacherChatRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/generator': typeof TeacherGeneratorRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/questions': typeof TeacherQuestionsRouteWithChildren
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/teacher/revenue': typeof TeacherRevenueRoute
  '/teacher/rewards': typeof TeacherRewardsRoute
  '/teacher/sessions': typeof TeacherSessionsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/team': typeof TeacherTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/assistant/': typeof AssistantIndexRoute
  '/content/': typeof ContentIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/student/': typeof StudentIndexRoute
  '/super/': typeof SuperIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/certificates/$certificateId': typeof StudentCertificatesCertificateIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRouteWithChildren
  '/teacher/questions/create': typeof TeacherQuestionsCreateRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/student/courses/$courseId/continue': typeof StudentCoursesCourseIdContinueRoute
  '/student/courses/$courseId/enroll': typeof StudentCoursesCourseIdEnrollRoute
  '/student/courses/$courseId/resources': typeof StudentCoursesCourseIdResourcesRoute
  '/student/courses/$courseId/session': typeof StudentCoursesCourseIdSessionRoute
  '/student/courses/$courseId/': typeof StudentCoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/student'
    | '/admin/banners'
    | '/admin/courses'
    | '/admin/notifications'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/assistant/analyze'
    | '/assistant/explain'
    | '/assistant/solve'
    | '/assistant/study-plan'
    | '/content/curriculum'
    | '/content/import'
    | '/content/lesson-review'
    | '/content/media'
    | '/content/question-review'
    | '/courses/$courseId'
    | '/developer/api-health'
    | '/developer/backend'
    | '/developer/deployments'
    | '/developer/error-logs'
    | '/developer/feature-flags'
    | '/developer/frontend'
    | '/developer/versions'
    | '/finance/coupons'
    | '/finance/invoices'
    | '/finance/payments'
    | '/finance/revenue'
    | '/finance/subscriptions'
    | '/parent/attendance'
    | '/parent/homework'
    | '/parent/messages'
    | '/parent/progress'
    | '/questions/wrong'
    | '/quiz/start'
    | '/student/certificates'
    | '/student/course-details'
    | '/student/leaderboard'
    | '/student/lesson'
    | '/student/notes'
    | '/student/notifications'
    | '/student/progress'
    | '/student/wallet'
    | '/student/wrong-questions'
    | '/super/access-matrix'
    | '/super/analytics'
    | '/super/audit'
    | '/super/system'
    | '/teacher/analytics'
    | '/teacher/assignments'
    | '/teacher/chapters'
    | '/teacher/chat'
    | '/teacher/courses'
    | '/teacher/generator'
    | '/teacher/lessons'
    | '/teacher/questions'
    | '/teacher/quizzes'
    | '/teacher/revenue'
    | '/teacher/rewards'
    | '/teacher/sessions'
    | '/teacher/students'
    | '/teacher/team'
    | '/admin/'
    | '/assistant/'
    | '/content/'
    | '/courses/'
    | '/developer/'
    | '/finance/'
    | '/parent/'
    | '/questions/'
    | '/student/'
    | '/super/'
    | '/teacher/'
    | '/student/certificates/$certificateId'
    | '/student/courses/$courseId'
    | '/teacher/questions/create'
    | '/student/courses/'
    | '/student/courses/$courseId/continue'
    | '/student/courses/$courseId/enroll'
    | '/student/courses/$courseId/resources'
    | '/student/courses/$courseId/session'
    | '/student/courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/admin/banners'
    | '/admin/courses'
    | '/admin/notifications'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/assistant/analyze'
    | '/assistant/explain'
    | '/assistant/solve'
    | '/assistant/study-plan'
    | '/content/curriculum'
    | '/content/import'
    | '/content/lesson-review'
    | '/content/media'
    | '/content/question-review'
    | '/courses/$courseId'
    | '/developer/api-health'
    | '/developer/backend'
    | '/developer/deployments'
    | '/developer/error-logs'
    | '/developer/feature-flags'
    | '/developer/frontend'
    | '/developer/versions'
    | '/finance/coupons'
    | '/finance/invoices'
    | '/finance/payments'
    | '/finance/revenue'
    | '/finance/subscriptions'
    | '/parent/attendance'
    | '/parent/homework'
    | '/parent/messages'
    | '/parent/progress'
    | '/questions/wrong'
    | '/quiz/start'
    | '/student/certificates'
    | '/student/course-details'
    | '/student/leaderboard'
    | '/student/lesson'
    | '/student/notes'
    | '/student/notifications'
    | '/student/progress'
    | '/student/wallet'
    | '/student/wrong-questions'
    | '/super/access-matrix'
    | '/super/analytics'
    | '/super/audit'
    | '/super/system'
    | '/teacher/analytics'
    | '/teacher/assignments'
    | '/teacher/chapters'
    | '/teacher/chat'
    | '/teacher/courses'
    | '/teacher/generator'
    | '/teacher/lessons'
    | '/teacher/questions'
    | '/teacher/quizzes'
    | '/teacher/revenue'
    | '/teacher/rewards'
    | '/teacher/sessions'
    | '/teacher/students'
    | '/teacher/team'
    | '/admin'
    | '/assistant'
    | '/content'
    | '/courses'
    | '/developer'
    | '/finance'
    | '/parent'
    | '/questions'
    | '/student'
    | '/super'
    | '/teacher'
    | '/student/certificates/$certificateId'
    | '/teacher/questions/create'
    | '/student/courses'
    | '/student/courses/$courseId/continue'
    | '/student/courses/$courseId/enroll'
    | '/student/courses/$courseId/resources'
    | '/student/courses/$courseId/session'
    | '/student/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/student'
    | '/admin/banners'
    | '/admin/courses'
    | '/admin/notifications'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/assistant/analyze'
    | '/assistant/explain'
    | '/assistant/solve'
    | '/assistant/study-plan'
    | '/content/curriculum'
    | '/content/import'
    | '/content/lesson-review'
    | '/content/media'
    | '/content/question-review'
    | '/courses/$courseId'
    | '/developer/api-health'
    | '/developer/backend'
    | '/developer/deployments'
    | '/developer/error-logs'
    | '/developer/feature-flags'
    | '/developer/frontend'
    | '/developer/versions'
    | '/finance/coupons'
    | '/finance/invoices'
    | '/finance/payments'
    | '/finance/revenue'
    | '/finance/subscriptions'
    | '/parent/attendance'
    | '/parent/homework'
    | '/parent/messages'
    | '/parent/progress'
    | '/questions/wrong'
    | '/quiz/start'
    | '/student/certificates'
    | '/student/course-details'
    | '/student/leaderboard'
    | '/student/lesson'
    | '/student/notes'
    | '/student/notifications'
    | '/student/progress'
    | '/student/wallet'
    | '/student/wrong-questions'
    | '/super/access-matrix'
    | '/super/analytics'
    | '/super/audit'
    | '/super/system'
    | '/teacher/analytics'
    | '/teacher/assignments'
    | '/teacher/chapters'
    | '/teacher/chat'
    | '/teacher/courses'
    | '/teacher/generator'
    | '/teacher/lessons'
    | '/teacher/questions'
    | '/teacher/quizzes'
    | '/teacher/revenue'
    | '/teacher/rewards'
    | '/teacher/sessions'
    | '/teacher/students'
    | '/teacher/team'
    | '/admin/'
    | '/assistant/'
    | '/content/'
    | '/courses/'
    | '/developer/'
    | '/finance/'
    | '/parent/'
    | '/questions/'
    | '/student/'
    | '/super/'
    | '/teacher/'
    | '/student/certificates/$certificateId'
    | '/student/courses/$courseId'
    | '/teacher/questions/create'
    | '/student/courses/'
    | '/student/courses/$courseId/continue'
    | '/student/courses/$courseId/enroll'
    | '/student/courses/$courseId/resources'
    | '/student/courses/$courseId/session'
    | '/student/courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AssistantAnalyzeRoute: typeof AssistantAnalyzeRoute
  AssistantExplainRoute: typeof AssistantExplainRoute
  AssistantSolveRoute: typeof AssistantSolveRoute
  AssistantStudyPlanRoute: typeof AssistantStudyPlanRoute
  ContentCurriculumRoute: typeof ContentCurriculumRoute
  ContentImportRoute: typeof ContentImportRoute
  ContentLessonReviewRoute: typeof ContentLessonReviewRoute
  ContentMediaRoute: typeof ContentMediaRoute
  ContentQuestionReviewRoute: typeof ContentQuestionReviewRoute
  DeveloperApiHealthRoute: typeof DeveloperApiHealthRoute
  DeveloperBackendRoute: typeof DeveloperBackendRoute
  DeveloperDeploymentsRoute: typeof DeveloperDeploymentsRoute
  DeveloperErrorLogsRoute: typeof DeveloperErrorLogsRoute
  DeveloperFeatureFlagsRoute: typeof DeveloperFeatureFlagsRoute
  DeveloperFrontendRoute: typeof DeveloperFrontendRoute
  DeveloperVersionsRoute: typeof DeveloperVersionsRoute
  FinanceCouponsRoute: typeof FinanceCouponsRoute
  FinanceInvoicesRoute: typeof FinanceInvoicesRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinanceRevenueRoute: typeof FinanceRevenueRoute
  FinanceSubscriptionsRoute: typeof FinanceSubscriptionsRoute
  ParentAttendanceRoute: typeof ParentAttendanceRoute
  ParentHomeworkRoute: typeof ParentHomeworkRoute
  ParentMessagesRoute: typeof ParentMessagesRoute
  ParentProgressRoute: typeof ParentProgressRoute
  QuestionsWrongRoute: typeof QuestionsWrongRoute
  QuizStartRoute: typeof QuizStartRoute
  SuperAccessMatrixRoute: typeof SuperAccessMatrixRoute
  SuperAnalyticsRoute: typeof SuperAnalyticsRoute
  SuperAuditRoute: typeof SuperAuditRoute
  SuperSystemRoute: typeof SuperSystemRoute
  TeacherAnalyticsRoute: typeof TeacherAnalyticsRoute
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherChaptersRoute: typeof TeacherChaptersRoute
  TeacherChatRoute: typeof TeacherChatRoute
  TeacherCoursesRoute: typeof TeacherCoursesRoute
  TeacherGeneratorRoute: typeof TeacherGeneratorRoute
  TeacherLessonsRoute: typeof TeacherLessonsRoute
  TeacherQuestionsRoute: typeof TeacherQuestionsRouteWithChildren
  TeacherQuizzesRoute: typeof TeacherQuizzesRoute
  TeacherRevenueRoute: typeof TeacherRevenueRoute
  TeacherRewardsRoute: typeof TeacherRewardsRoute
  TeacherSessionsRoute: typeof TeacherSessionsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherTeamRoute: typeof TeacherTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
  ContentIndexRoute: typeof ContentIndexRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  ParentIndexRoute: typeof ParentIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  SuperIndexRoute: typeof SuperIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/super'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/team': {
      id: '/teacher/team'
      path: '/teacher/team'
      fullPath: '/teacher/team'
      preLoaderRoute: typeof TeacherTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/teacher/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/sessions': {
      id: '/teacher/sessions'
      path: '/teacher/sessions'
      fullPath: '/teacher/sessions'
      preLoaderRoute: typeof TeacherSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/rewards': {
      id: '/teacher/rewards'
      path: '/teacher/rewards'
      fullPath: '/teacher/rewards'
      preLoaderRoute: typeof TeacherRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/revenue': {
      id: '/teacher/revenue'
      path: '/teacher/revenue'
      fullPath: '/teacher/revenue'
      preLoaderRoute: typeof TeacherRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/quizzes': {
      id: '/teacher/quizzes'
      path: '/teacher/quizzes'
      fullPath: '/teacher/quizzes'
      preLoaderRoute: typeof TeacherQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/questions': {
      id: '/teacher/questions'
      path: '/teacher/questions'
      fullPath: '/teacher/questions'
      preLoaderRoute: typeof TeacherQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/lessons': {
      id: '/teacher/lessons'
      path: '/teacher/lessons'
      fullPath: '/teacher/lessons'
      preLoaderRoute: typeof TeacherLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/generator': {
      id: '/teacher/generator'
      path: '/teacher/generator'
      fullPath: '/teacher/generator'
      preLoaderRoute: typeof TeacherGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/courses': {
      id: '/teacher/courses'
      path: '/teacher/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/chat': {
      id: '/teacher/chat'
      path: '/teacher/chat'
      fullPath: '/teacher/chat'
      preLoaderRoute: typeof TeacherChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/chapters': {
      id: '/teacher/chapters'
      path: '/teacher/chapters'
      fullPath: '/teacher/chapters'
      preLoaderRoute: typeof TeacherChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/teacher/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/analytics': {
      id: '/teacher/analytics'
      path: '/teacher/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof TeacherAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/system': {
      id: '/super/system'
      path: '/super/system'
      fullPath: '/super/system'
      preLoaderRoute: typeof SuperSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/audit': {
      id: '/super/audit'
      path: '/super/audit'
      fullPath: '/super/audit'
      preLoaderRoute: typeof SuperAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/analytics': {
      id: '/super/analytics'
      path: '/super/analytics'
      fullPath: '/super/analytics'
      preLoaderRoute: typeof SuperAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/access-matrix': {
      id: '/super/access-matrix'
      path: '/super/access-matrix'
      fullPath: '/super/access-matrix'
      preLoaderRoute: typeof SuperAccessMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/wrong-questions': {
      id: '/student/wrong-questions'
      path: '/wrong-questions'
      fullPath: '/student/wrong-questions'
      preLoaderRoute: typeof StudentWrongQuestionsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/wallet': {
      id: '/student/wallet'
      path: '/wallet'
      fullPath: '/student/wallet'
      preLoaderRoute: typeof StudentWalletRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notes': {
      id: '/student/notes'
      path: '/notes'
      fullPath: '/student/notes'
      preLoaderRoute: typeof StudentNotesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lesson': {
      id: '/student/lesson'
      path: '/lesson'
      fullPath: '/student/lesson'
      preLoaderRoute: typeof StudentLessonRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/leaderboard': {
      id: '/student/leaderboard'
      path: '/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof StudentLeaderboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/course-details': {
      id: '/student/course-details'
      path: '/course-details'
      fullPath: '/student/course-details'
      preLoaderRoute: typeof StudentCourseDetailsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/quiz/start': {
      id: '/quiz/start'
      path: '/quiz/start'
      fullPath: '/quiz/start'
      preLoaderRoute: typeof QuizStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/wrong': {
      id: '/questions/wrong'
      path: '/questions/wrong'
      fullPath: '/questions/wrong'
      preLoaderRoute: typeof QuestionsWrongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/progress': {
      id: '/parent/progress'
      path: '/parent/progress'
      fullPath: '/parent/progress'
      preLoaderRoute: typeof ParentProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/messages': {
      id: '/parent/messages'
      path: '/parent/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof ParentMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/homework': {
      id: '/parent/homework'
      path: '/parent/homework'
      fullPath: '/parent/homework'
      preLoaderRoute: typeof ParentHomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/attendance': {
      id: '/parent/attendance'
      path: '/parent/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof ParentAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/subscriptions': {
      id: '/finance/subscriptions'
      path: '/finance/subscriptions'
      fullPath: '/finance/subscriptions'
      preLoaderRoute: typeof FinanceSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/revenue': {
      id: '/finance/revenue'
      path: '/finance/revenue'
      fullPath: '/finance/revenue'
      preLoaderRoute: typeof FinanceRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/invoices': {
      id: '/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof FinanceInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/coupons': {
      id: '/finance/coupons'
      path: '/finance/coupons'
      fullPath: '/finance/coupons'
      preLoaderRoute: typeof FinanceCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/versions': {
      id: '/developer/versions'
      path: '/developer/versions'
      fullPath: '/developer/versions'
      preLoaderRoute: typeof DeveloperVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/frontend': {
      id: '/developer/frontend'
      path: '/developer/frontend'
      fullPath: '/developer/frontend'
      preLoaderRoute: typeof DeveloperFrontendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/feature-flags': {
      id: '/developer/feature-flags'
      path: '/developer/feature-flags'
      fullPath: '/developer/feature-flags'
      preLoaderRoute: typeof DeveloperFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/error-logs': {
      id: '/developer/error-logs'
      path: '/developer/error-logs'
      fullPath: '/developer/error-logs'
      preLoaderRoute: typeof DeveloperErrorLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/deployments': {
      id: '/developer/deployments'
      path: '/developer/deployments'
      fullPath: '/developer/deployments'
      preLoaderRoute: typeof DeveloperDeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/backend': {
      id: '/developer/backend'
      path: '/developer/backend'
      fullPath: '/developer/backend'
      preLoaderRoute: typeof DeveloperBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/api-health': {
      id: '/developer/api-health'
      path: '/developer/api-health'
      fullPath: '/developer/api-health'
      preLoaderRoute: typeof DeveloperApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/content/question-review': {
      id: '/content/question-review'
      path: '/content/question-review'
      fullPath: '/content/question-review'
      preLoaderRoute: typeof ContentQuestionReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/media': {
      id: '/content/media'
      path: '/content/media'
      fullPath: '/content/media'
      preLoaderRoute: typeof ContentMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/lesson-review': {
      id: '/content/lesson-review'
      path: '/content/lesson-review'
      fullPath: '/content/lesson-review'
      preLoaderRoute: typeof ContentLessonReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/import': {
      id: '/content/import'
      path: '/content/import'
      fullPath: '/content/import'
      preLoaderRoute: typeof ContentImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/curriculum': {
      id: '/content/curriculum'
      path: '/content/curriculum'
      fullPath: '/content/curriculum'
      preLoaderRoute: typeof ContentCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/study-plan': {
      id: '/assistant/study-plan'
      path: '/assistant/study-plan'
      fullPath: '/assistant/study-plan'
      preLoaderRoute: typeof AssistantStudyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/solve': {
      id: '/assistant/solve'
      path: '/assistant/solve'
      fullPath: '/assistant/solve'
      preLoaderRoute: typeof AssistantSolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/explain': {
      id: '/assistant/explain'
      path: '/assistant/explain'
      fullPath: '/assistant/explain'
      preLoaderRoute: typeof AssistantExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/analyze': {
      id: '/assistant/analyze'
      path: '/assistant/analyze'
      fullPath: '/assistant/analyze'
      preLoaderRoute: typeof AssistantAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses/': {
      id: '/student/courses/'
      path: '/courses'
      fullPath: '/student/courses/'
      preLoaderRoute: typeof StudentCoursesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/questions/create': {
      id: '/teacher/questions/create'
      path: '/create'
      fullPath: '/teacher/questions/create'
      preLoaderRoute: typeof TeacherQuestionsCreateRouteImport
      parentRoute: typeof TeacherQuestionsRoute
    }
    '/student/courses/$courseId': {
      id: '/student/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof StudentCoursesCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificates/$certificateId': {
      id: '/student/certificates/$certificateId'
      path: '/$certificateId'
      fullPath: '/student/certificates/$certificateId'
      preLoaderRoute: typeof StudentCertificatesCertificateIdRouteImport
      parentRoute: typeof StudentCertificatesRoute
    }
    '/student/courses/$courseId/': {
      id: '/student/courses/$courseId/'
      path: '/'
      fullPath: '/student/courses/$courseId/'
      preLoaderRoute: typeof StudentCoursesCourseIdIndexRouteImport
      parentRoute: typeof StudentCoursesCourseIdRoute
    }
    '/student/courses/$courseId/session': {
      id: '/student/courses/$courseId/session'
      path: '/session'
      fullPath: '/student/courses/$courseId/session'
      preLoaderRoute: typeof StudentCoursesCourseIdSessionRouteImport
      parentRoute: typeof StudentCoursesCourseIdRoute
    }
    '/student/courses/$courseId/resources': {
      id: '/student/courses/$courseId/resources'
      path: '/resources'
      fullPath: '/student/courses/$courseId/resources'
      preLoaderRoute: typeof StudentCoursesCourseIdResourcesRouteImport
      parentRoute: typeof StudentCoursesCourseIdRoute
    }
    '/student/courses/$courseId/enroll': {
      id: '/student/courses/$courseId/enroll'
      path: '/enroll'
      fullPath: '/student/courses/$courseId/enroll'
      preLoaderRoute: typeof StudentCoursesCourseIdEnrollRouteImport
      parentRoute: typeof StudentCoursesCourseIdRoute
    }
    '/student/courses/$courseId/continue': {
      id: '/student/courses/$courseId/continue'
      path: '/continue'
      fullPath: '/student/courses/$courseId/continue'
      preLoaderRoute: typeof StudentCoursesCourseIdContinueRouteImport
      parentRoute: typeof StudentCoursesCourseIdRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface StudentCertificatesRouteChildren {
  StudentCertificatesCertificateIdRoute: typeof StudentCertificatesCertificateIdRoute
}

const StudentCertificatesRouteChildren: StudentCertificatesRouteChildren = {
  StudentCertificatesCertificateIdRoute: StudentCertificatesCertificateIdRoute,
}

const StudentCertificatesRouteWithChildren =
  StudentCertificatesRoute._addFileChildren(StudentCertificatesRouteChildren)

interface StudentCoursesCourseIdRouteChildren {
  StudentCoursesCourseIdContinueRoute: typeof StudentCoursesCourseIdContinueRoute
  StudentCoursesCourseIdEnrollRoute: typeof StudentCoursesCourseIdEnrollRoute
  StudentCoursesCourseIdResourcesRoute: typeof StudentCoursesCourseIdResourcesRoute
  StudentCoursesCourseIdSessionRoute: typeof StudentCoursesCourseIdSessionRoute
  StudentCoursesCourseIdIndexRoute: typeof StudentCoursesCourseIdIndexRoute
}

const StudentCoursesCourseIdRouteChildren: StudentCoursesCourseIdRouteChildren =
  {
    StudentCoursesCourseIdContinueRoute: StudentCoursesCourseIdContinueRoute,
    StudentCoursesCourseIdEnrollRoute: StudentCoursesCourseIdEnrollRoute,
    StudentCoursesCourseIdResourcesRoute: StudentCoursesCourseIdResourcesRoute,
    StudentCoursesCourseIdSessionRoute: StudentCoursesCourseIdSessionRoute,
    StudentCoursesCourseIdIndexRoute: StudentCoursesCourseIdIndexRoute,
  }

const StudentCoursesCourseIdRouteWithChildren =
  StudentCoursesCourseIdRoute._addFileChildren(
    StudentCoursesCourseIdRouteChildren,
  )

interface StudentRouteChildren {
  StudentCertificatesRoute: typeof StudentCertificatesRouteWithChildren
  StudentCourseDetailsRoute: typeof StudentCourseDetailsRoute
  StudentLeaderboardRoute: typeof StudentLeaderboardRoute
  StudentLessonRoute: typeof StudentLessonRoute
  StudentNotesRoute: typeof StudentNotesRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentWalletRoute: typeof StudentWalletRoute
  StudentWrongQuestionsRoute: typeof StudentWrongQuestionsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCoursesCourseIdRoute: typeof StudentCoursesCourseIdRouteWithChildren
  StudentCoursesIndexRoute: typeof StudentCoursesIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCertificatesRoute: StudentCertificatesRouteWithChildren,
  StudentCourseDetailsRoute: StudentCourseDetailsRoute,
  StudentLeaderboardRoute: StudentLeaderboardRoute,
  StudentLessonRoute: StudentLessonRoute,
  StudentNotesRoute: StudentNotesRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentWalletRoute: StudentWalletRoute,
  StudentWrongQuestionsRoute: StudentWrongQuestionsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentCoursesCourseIdRoute: StudentCoursesCourseIdRouteWithChildren,
  StudentCoursesIndexRoute: StudentCoursesIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherQuestionsRouteChildren {
  TeacherQuestionsCreateRoute: typeof TeacherQuestionsCreateRoute
}

const TeacherQuestionsRouteChildren: TeacherQuestionsRouteChildren = {
  TeacherQuestionsCreateRoute: TeacherQuestionsCreateRoute,
}

const TeacherQuestionsRouteWithChildren =
  TeacherQuestionsRoute._addFileChildren(TeacherQuestionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
  AdminBannersRoute: AdminBannersRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AssistantAnalyzeRoute: AssistantAnalyzeRoute,
  AssistantExplainRoute: AssistantExplainRoute,
  AssistantSolveRoute: AssistantSolveRoute,
  AssistantStudyPlanRoute: AssistantStudyPlanRoute,
  ContentCurriculumRoute: ContentCurriculumRoute,
  ContentImportRoute: ContentImportRoute,
  ContentLessonReviewRoute: ContentLessonReviewRoute,
  ContentMediaRoute: ContentMediaRoute,
  ContentQuestionReviewRoute: ContentQuestionReviewRoute,
  DeveloperApiHealthRoute: DeveloperApiHealthRoute,
  DeveloperBackendRoute: DeveloperBackendRoute,
  DeveloperDeploymentsRoute: DeveloperDeploymentsRoute,
  DeveloperErrorLogsRoute: DeveloperErrorLogsRoute,
  DeveloperFeatureFlagsRoute: DeveloperFeatureFlagsRoute,
  DeveloperFrontendRoute: DeveloperFrontendRoute,
  DeveloperVersionsRoute: DeveloperVersionsRoute,
  FinanceCouponsRoute: FinanceCouponsRoute,
  FinanceInvoicesRoute: FinanceInvoicesRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinanceRevenueRoute: FinanceRevenueRoute,
  FinanceSubscriptionsRoute: FinanceSubscriptionsRoute,
  ParentAttendanceRoute: ParentAttendanceRoute,
  ParentHomeworkRoute: ParentHomeworkRoute,
  ParentMessagesRoute: ParentMessagesRoute,
  ParentProgressRoute: ParentProgressRoute,
  QuestionsWrongRoute: QuestionsWrongRoute,
  QuizStartRoute: QuizStartRoute,
  SuperAccessMatrixRoute: SuperAccessMatrixRoute,
  SuperAnalyticsRoute: SuperAnalyticsRoute,
  SuperAuditRoute: SuperAuditRoute,
  SuperSystemRoute: SuperSystemRoute,
  TeacherAnalyticsRoute: TeacherAnalyticsRoute,
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherChaptersRoute: TeacherChaptersRoute,
  TeacherChatRoute: TeacherChatRoute,
  TeacherCoursesRoute: TeacherCoursesRoute,
  TeacherGeneratorRoute: TeacherGeneratorRoute,
  TeacherLessonsRoute: TeacherLessonsRoute,
  TeacherQuestionsRoute: TeacherQuestionsRouteWithChildren,
  TeacherQuizzesRoute: TeacherQuizzesRoute,
  TeacherRevenueRoute: TeacherRevenueRoute,
  TeacherRewardsRoute: TeacherRewardsRoute,
  TeacherSessionsRoute: TeacherSessionsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherTeamRoute: TeacherTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
  AssistantIndexRoute: AssistantIndexRoute,
  ContentIndexRoute: ContentIndexRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  ParentIndexRoute: ParentIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  SuperIndexRoute: SuperIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
