import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

type Theme = "light" | "dark";
type Lang = "en" | "ar";

interface AppState {
  theme: Theme;
  toggleTheme: () => void;
  setTheme: (t: Theme) => void;
  lang: Lang;
  setLang: (l: Lang) => void;
  toggleLang: () => void;
  dir: "ltr" | "rtl";
  t: (key: string) => string;
}

const AppContext = createContext<AppState | null>(null);

const dict: Record<string, { en: string; ar: string }> = {
  "student.upcomingEvents": { en: "Upcoming Events", ar: "الأحداث القادمة" },
  "student.dontMissAnything": { en: "Don't miss anything", ar: "لا تفوّت أي شيء" },
  "student.achievements": { en: "Achievements", ar: "الإنجازات" },
  "student.keepItUp": { en: "You're doing great! Keep it up!", ar: "أداؤك رائع! واصل التقدم!" },
  "student.dayStreak": { en: "Day Streak", ar: "سلسلة الأيام" },
  "student.totalXp": { en: "Total XP", ar: "إجمالي نقاط الخبرة" },
  "student.weeklyRank": { en: "Weekly Rank", ar: "الترتيب الأسبوعي" },
  "student.badgesEarned": { en: "Badges Earned", ar: "الشارات المكتسبة" },
  "student.bestSubject": { en: "Best Subject", ar: "أفضل مادة" },
  "student.awards": { en: "Awards", ar: "الجوائز" },
  "student.subjectDistribution": { en: "Subject Distribution", ar: "توزيع المواد" },
  "student.scoreAcrossSubjects": { en: "Your score across subjects", ar: "درجاتك عبر المواد" },
  "student.aiCoach": { en: "AI Coach", ar: "المدرب الذكي" },
  "student.personalStudyCoach": { en: "Your personal study coach", ar: "مدربك الشخصي للدراسة" },
  "student.buildStudyPlan": { en: "Build Study Plan", ar: "أنشئ خطة دراسة" },
  "student.generateQuiz": { en: "Generate Quiz", ar: "أنشئ اختبارًا" },
  "student.explainWeakPoints": { en: "Explain Weak Points", ar: "اشرح نقاط الضعف" },
  "student.reviewDueLessons": { en: "Review Due Lessons", ar: "راجع الدروس المستحقة" },
  "student.askAnything": { en: "Ask Anything", ar: "اسأل أي شيء" },
  "nav.home": { en: "Home", ar: "الرئيسية" },
  "nav.about": { en: "About", ar: "من نحن" },
  "nav.courses": { en: "Courses", ar: "الدورات" },
  "nav.pricing": { en: "Pricing", ar: "الأسعار" },
  "nav.contact": { en: "Contact", ar: "تواصل" },
  "nav.login": { en: "Login", ar: "تسجيل الدخول" },
  "nav.register": { en: "Register", ar: "إنشاء حساب" },
  "nav.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "nav.learning": { en: "Learning", ar: "التعلم" },
  "nav.practice": { en: "Practice", ar: "التدريب" },
  "nav.rewards": { en: "Rewards", ar: "المكافآت" },
  "nav.more": { en: "More", ar: "المزيد" },
  "nav.communication": { en: "Communication", ar: "التواصل" },
  "role.student": { en: "Student", ar: "طالب" },
  "role.studentTagline": { en: "Learn & grow", ar: "تعلّم وتقدّم" },
  "role.teacher": { en: "Teacher", ar: "معلم" },
  "role.teacherTagline": { en: "Your academy workspace", ar: "مساحة عمل الأكاديمية" },
  "student.smartRevision": { en: "Smart Revision", ar: "مراجعة ذكية" },
  "student.myNotes": { en: "My Notes", ar: "ملاحظاتي" },
  "student.progress": { en: "Progress", ar: "التقدم" },
  "student.questionBank": { en: "Question Bank", ar: "بنك الأسئلة" },
  "student.wrongQuestions": { en: "Wrong Questions", ar: "الأسئلة الخاطئة" },
  "student.trophyRoom": { en: "Trophy Room", ar: "غرفة الإنجازات" },
  "student.leaderboard": { en: "Leaderboard", ar: "لوحة الصدارة" },
  "student.certificates": { en: "Certificates", ar: "الشهادات" },
  "student.wallet": { en: "Wallet", ar: "المحفظة" },
  "student.aiAssistant": { en: "AI Assistant", ar: "المساعد الذكي" },
  "student.notifications": { en: "Notifications", ar: "الإشعارات" },
  "student.goodEvening": { en: "Good evening", ar: "مساء الخير" },
  "student.dashboardSubtitle": { en: "Ready to crush your goals today!", ar: "جاهز لتحقيق أهدافك اليوم!" },
  "student.dailyMissions": { en: "Daily Missions", ar: "مهام اليوم" },
  "student.complete": { en: "complete", ar: "مكتملة" },
  "student.continueWhereLeftOff": { en: "Continue where you left off", ar: "تابع من حيث توقفت" },
  "student.noCoursesYet": { en: "No courses yet", ar: "لا توجد دورات بعد" },
  "student.learningAdventureStarts": { en: "Your learning adventure starts here.", ar: "تبدأ رحلة التعلم من هنا." },
  "student.browseCourses": { en: "Browse Courses", ar: "تصفح الدورات" },
  "teacher.workspaceTitle": { en: "Teacher Workspace", ar: "مساحة عمل المعلم" },
  "teacher.thisWeek": { en: "this week", ar: "هذا الأسبوع" },
  "teacher.createSession": { en: "Create Session", ar: "إنشاء حصة" },
  "teacher.addQuiz": { en: "Add Quiz", ar: "إضافة اختبار" },
  "teacher.uploadMaterial": { en: "Upload Material", ar: "رفع مادة" },
  "teacher.addQuestions": { en: "Add Questions", ar: "إضافة أسئلة" },
  "teacher.announcement": { en: "Announcement", ar: "إعلان" },
  "teacher.viewRevenue": { en: "View Revenue", ar: "عرض الإيرادات" },
  "teacher.essayGradingQueue": { en: "Essay Grading Queue", ar: "قائمة تصحيح المقالات" },
  "teacher.recentSales": { en: "Recent Sales", ar: "آخر المبيعات" },
  "teacher.paymentId": { en: "Payment ID", ar: "رقم الدفع" },
  "teacher.item": { en: "Item", ar: "العنصر" },
  "teacher.date": { en: "Date", ar: "التاريخ" },
  "teacher.activeCourses": { en: "Active Courses", ar: "الدورات النشطة" },
  "teacher.teamMessages": { en: "Team Messages", ar: "رسائل الفريق" },
  "teacher.unread": { en: "unread", ar: "غير مقروءة" },
  "teacher.activeSessions": { en: "Active Sessions", ar: "الحصص النشطة" },
  "Must Do Today": { en: "Must Do Today", ar: "يجب إنجازه اليوم" },
  "Recommended": { en: "Recommended", ar: "موصى به" },
  "Optional": { en: "Optional", ar: "اختياري" },
  "(if you have time)": { en: "(if you have time)", ar: "(إذا كان لديك وقت)" },
  "Today's Mission": { en: "Today's Mission", ar: "مهمة اليوم" },
  "What will you achieve today?": { en: "What will you achieve today?", ar: "ماذا ستحقق اليوم؟" },
  "Start Today": { en: "Start Today", ar: "ابدأ اليوم" },
  "Discipline today": { en: "Discipline today", ar: "انضباط اليوم" },
  "Success tomorrow": { en: "Success tomorrow", ar: "نجاح الغد" },
  "Resume": { en: "Resume", ar: "استئناف" },
  "Weak Points": { en: "Weak Points", ar: "نقاط الضعف" },
  "Focus on what matters": { en: "Focus on what matters", ar: "ركّز على الأهم" },
  "High": { en: "High", ar: "عالٍ" },
  "Medium": { en: "Medium", ar: "متوسط" },
  "Low": { en: "Low", ar: "منخفض" },
  "Revision Due": { en: "Revision Due", ar: "مراجعة مستحقة" },
  "Based on memory system": { en: "Based on memory system", ar: "حسب نظام الذاكرة" },
  "Due today": { en: "Due today", ar: "مستحق اليوم" },
  "In 1 day": { en: "In 1 day", ar: "خلال يوم" },
  "Attention Needed": { en: "Attention Needed", ar: "بحاجة إلى انتباه" },
  "Important updates": { en: "Important updates", ar: "تحديثات مهمة" },
  "Overdue": { en: "Overdue", ar: "متأخر" },
  "Due tomorrow": { en: "Due tomorrow", ar: "مستحق غدًا" },
  "Favorite Course": { en: "Favorite Course", ar: "الدورة المفضلة" },
  "Your most studied this week": { en: "Your most studied this week", ar: "الأكثر دراسة هذا الأسبوع" },
  "Hours this week": { en: "Hours this week", ar: "ساعات هذا الأسبوع" },
  "Lessons completed": { en: "Lessons completed", ar: "دروس مكتملة" },
  "Continue Learning": { en: "Continue Learning", ar: "متابعة التعلم" },
  "hero.title": { en: "Learn Smarter with CLASSZ", ar: "تعلّم بذكاء مع CLASSZ" },
  "hero.subtitle": {
    en: "A premium learning platform that blends structured courses, gamified progress, and an AI study assistant for secondary students and teachers.",
    ar: "منصة تعليمية متميزة تجمع بين الدورات المنظمة والتقدم التفاعلي ومساعد ذكاء اصطناعي للطلاب والمعلمين.",
  },
  "hero.getStarted": { en: "Get started free", ar: "ابدأ مجانًا" },
  "common.search": { en: "Search", ar: "بحث" },
  "common.globalSearchPlaceholder": { en: "Search courses, lessons, students…", ar: "ابحث في الدورات والدروس والطلاب…" },
  "common.viewAll": { en: "View all", ar: "عرض الكل" },
  "common.logout": { en: "Log out", ar: "تسجيل الخروج" },
  "common.settings": { en: "Settings", ar: "الإعدادات" },
  "workspace.title": { en: "Workspace", ar: "مساحة العمل" },
  "workspace.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "workspace.myCourses": { en: "My Courses", ar: "دوراتي" },
  "workspace.contentStudio": { en: "Content Studio", ar: "استوديو المحتوى" },

  // Team Module
  "team.title": { en: "Team", ar: "الفريق" },
  "team.overview": { en: "Overview", ar: "نظرة عامة" },
  "team.members": { en: "Members", ar: "الأعضاء" },
  "team.recruitment": { en: "Recruitment", ar: "التوظيف" },
  "team.applications": { en: "Applications", ar: "الطلبات" },
  "team.roles": { en: "Roles & Permissions", ar: "الأدوار والصلاحيات" },
  "team.studentPods": { en: "Student Pods", ar: "مجموعات الطلاب" },
  "team.revenueSharing": { en: "Revenue Sharing", ar: "توزيع الأرباح" },
  "team.tasks": { en: "Tasks & Workflow", ar: "المهام وسير العمل" },
  "team.activityLogs": { en: "Activity Logs", ar: "سجل النشاط" },
  "team.invitations": { en: "Invitations", ar: "الدعوات" },
  "team.management": { en: "Team Management", ar: "إدارة الفريق" },
  "team.subtitle": { en: "Manage your academy staff and permissions", ar: "إدارة موظفي الأكاديمية والصلاحيات" },
  "team.totalMembers": { en: "Total Members", ar: "إجمالي الأعضاء" },
  "team.teachers": { en: "Teachers", ar: "المعلمون" },
  "team.assistantTeachers": { en: "Assistant Teachers", ar: "المعلمون المساعدون" },
  "team.contentManagers": { en: "Content Managers", ar: "مديرو المحتوى" },
  "team.finance": { en: "Finance", ar: "المالية" },
  "team.support": { en: "Support", ar: "الدعم" },
  "team.pendingInvitations": { en: "Pending Invitations", ar: "الدعوات المعلقة" },
  "team.recentActivity": { en: "Recent Activity", ar: "النشاط الأخير" },
  "team.quickActions": { en: "Quick Actions", ar: "إجراءات سريعة" },
  "team.addMember": { en: "Add Member", ar: "إضافة عضو" },
  "team.publishRecruitment": { en: "Publish Recruitment Post", ar: "نشر إعلان توظيف" },
  "team.reviewApplications": { en: "Review Applications", ar: "مراجعة الطلبات" },
  "team.assignStudents": { en: "Assign Students to Assistant", ar: "تعيين طلاب لمساعد" },
  "team.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "team.mobile": { en: "Mobile", ar: "الجوال" },
  "team.email": { en: "Email", ar: "البريد الإلكتروني" },
  "team.role": { en: "Role", ar: "الدور" },
  "team.assignedCourses": { en: "Assigned Courses", ar: "الدورات المعيّنة" },
  "team.username": { en: "Username", ar: "اسم المستخدم" },
  "team.password": { en: "Password", ar: "كلمة المرور" },
  "team.autoGenerate": { en: "Auto-generate", ar: "توليد تلقائي" },
  "team.sendCredentials": { en: "Send Credentials", ar: "إرسال بيانات الدخول" },
  "team.viaWhatsApp": { en: "Via WhatsApp", ar: "عبر واتساب" },
  "team.viaEmail": { en: "Via Email", ar: "عبر البريد" },
  "team.copyCredentials": { en: "Copy Credentials", ar: "نسخ البيانات" },
  "team.personalInfo": { en: "Personal Info", ar: "المعلومات الشخصية" },
  "team.permissions": { en: "Permissions", ar: "الصلاحيات" },
  "team.revenueShare": { en: "Revenue Share", ar: "حصة الأرباح" },
  "team.activityStats": { en: "Activity Stats", ar: "إحصائيات النشاط" },
  "team.status": { en: "Status", ar: "الحالة" },
  "team.lastActive": { en: "Last Active", ar: "آخر نشاط" },
  "team.actions": { en: "Actions", ar: "الإجراءات" },
  "team.jobTitle": { en: "Job Title", ar: "عنوان الوظيفة" },
  "team.jobType": { en: "Job Type", ar: "نوع الوظيفة" },
  "team.salaryType": { en: "Salary Type", ar: "نوع الراتب" },
  "team.salaryAmount": { en: "Salary Amount", ar: "قيمة الراتب" },
  "team.requirements": { en: "Requirements", ar: "المتطلبات" },
  "team.responsibilities": { en: "Responsibilities", ar: "المسؤوليات" },
  "team.experience": { en: "Required Experience", ar: "الخبرة المطلوبة" },
  "team.publish": { en: "Publish", ar: "نشر" },
  "team.draft": { en: "Draft", ar: "مسودة" },
  "team.applicantName": { en: "Applicant Name", ar: "اسم المتقدم" },
  "team.position": { en: "Position", ar: "الوظيفة" },
  "team.submittedDate": { en: "Submitted Date", ar: "تاريخ التقديم" },
  "team.new": { en: "New", ar: "جديد" },
  "team.shortlisted": { en: "Shortlisted", ar: "قائمة مختصرة" },
  "team.interview": { en: "Interview", ar: "مقابلة" },
  "team.accepted": { en: "Accepted", ar: "مقبول" },
  "team.rejected": { en: "Rejected", ar: "مرفوض" },
  "team.reject": { en: "Reject", ar: "رفض" },
  "team.shortlist": { en: "Shortlist", ar: "قائمة مختصرة" },
  "team.moveToInterview": { en: "Move to Interview", ar: "نقل للمقابلة" },
  "team.accept": { en: "Accept", ar: "قبول" },
  "team.createAccount": { en: "Create Team Account", ar: "إنشاء حساب الفريق" },
  "team.accountCreated": { en: "Account Created", ar: "تم إنشاء الحساب" },
  "team.cv": { en: "CV", ar: "السيرة الذاتية" },
  "team.introVideo": { en: "Intro Video", ar: "فيديو تعريفي" },
  "team.notes": { en: "Notes", ar: "ملاحظات" },
  "team.evaluationScore": { en: "Evaluation Score", ar: "درجة التقييم" },
  "team.customRole": { en: "Custom Role", ar: "دور مخصص" },
  "team.permissionMatrix": { en: "Permission Matrix", ar: "مصفوفة الصلاحيات" },
  "team.uploadMaterials": { en: "Upload Materials", ar: "رفع المواد" },
  "team.manageSessions": { en: "Manage Sessions", ar: "إدارة الحصص" },
  "team.createQuestions": { en: "Create Questions", ar: "إنشاء أسئلة" },
  "team.createQuizzes": { en: "Create Quizzes", ar: "إنشاء اختبارات" },
  "team.createHomework": { en: "Create Homework", ar: "إنشاء واجبات" },
  "team.createExams": { en: "Create Exams", ar: "إنشاء امتحانات" },
  "team.gradeEssays": { en: "Grade Essays", ar: "تصحيح المقالات" },
  "team.replyStudents": { en: "Reply to Students", ar: "الرد على الطلاب" },
  "team.contactParents": { en: "Contact Parents", ar: "التواصل مع أولياء الأمور" },
  "team.viewAnalytics": { en: "View Analytics", ar: "عرض التحليلات" },
  "team.managePayments": { en: "Manage Payments", ar: "إدارة المدفوعات" },
  "team.manageTeam": { en: "Manage Team", ar: "إدارة الفريق" },
  "team.manageSettings": { en: "Manage Settings", ar: "إدارة الإعدادات" },
  "team.teacher": { en: "Teacher", ar: "المعلم" },
  "team.assistantTeacher": { en: "Assistant Teacher", ar: "معلم مساعد" },
  "team.contentManager": { en: "Content Manager", ar: "مدير محتوى" },
  "team.moderator": { en: "Moderator", ar: "مشرف" },
  "team.developer": { en: "Developer", ar: "مطور" },
  "team.admin": { en: "Admin", ar: "مسؤول" },
  "team.groupName": { en: "Group Name", ar: "اسم المجموعة" },
  "team.studentCount": { en: "Number of Students", ar: "عدد الطلاب" },
  "team.riskSummary": { en: "Risk Summary", ar: "ملخص المخاطر" },
  "team.completionAvg": { en: "Completion Average", ar: "متوسط الإنجاز" },
  "team.unsubmittedHW": { en: "Unsubmitted Homework", ar: "واجبات لم تُسلّم" },
  "team.autoDistribute": { en: "Automatic Distribution", ar: "توزيع تلقائي" },
  "team.manualAssign": { en: "Manual Assignment", ar: "تعيين يدوي" },
  "team.fixedSalary": { en: "Fixed Salary", ar: "راتب ثابت" },
  "team.percentageShare": { en: "Percentage Share", ar: "حصة نسبية" },
  "team.perTask": { en: "Per Task", ar: "لكل مهمة" },
  "team.perGraded": { en: "Per Graded Assignment", ar: "لكل واجب مصحح" },
  "team.totalEarned": { en: "Total Earned", ar: "إجمالي المكتسب" },
  "team.paid": { en: "Paid", ar: "مدفوع" },
  "team.pending": { en: "Pending", ar: "معلق" },
  "team.todo": { en: "To Do", ar: "قيد الانتظار" },
  "team.inProgress": { en: "In Progress", ar: "قيد التنفيذ" },
  "team.review": { en: "Review", ar: "مراجعة" },
  "team.done": { en: "Done", ar: "تم" },
  "team.priority": { en: "Priority", ar: "الأولوية" },
  "team.dueDate": { en: "Due Date", ar: "تاريخ الاستحقاق" },
  "team.high": { en: "High", ar: "عالية" },
  "team.medium": { en: "Medium", ar: "متوسطة" },
  "team.low": { en: "Low", ar: "منخفضة" },
  "team.filterByMember": { en: "Filter by Member", ar: "تصفية حسب العضو" },
  "team.filterByAction": { en: "Filter by Action", ar: "تصفية حسب الإجراء" },
  "team.filterByDate": { en: "Filter by Date", ar: "تصفية حسب التاريخ" },
  "team.filterByCourse": { en: "Filter by Course", ar: "تصفية حسب الدورة" },
  "team.sentDate": { en: "Sent Date", ar: "تاريخ الإرسال" },
  "team.expiryDate": { en: "Expiry Date", ar: "تاريخ الانتهاء" },
  "team.expired": { en: "Expired", ar: "منتهي" },
  "team.revoked": { en: "Revoked", ar: "ملغي" },
  "team.resend": { en: "Resend", ar: "إعادة إرسال" },
  "team.revoke": { en: "Revoke", ar: "إلغاء" },
  "team.amount": { en: "Amount", ar: "المبلغ" },
  "team.compensationType": { en: "Compensation Type", ar: "نوع التعويض" },
  "team.save": { en: "Save", ar: "حفظ" },
  "team.cancel": { en: "Cancel", ar: "إلغاء" },
  "team.close": { en: "Close", ar: "إغلاق" },
  "team.edit": { en: "Edit", ar: "تعديل" },
  "team.delete": { en: "Delete", ar: "حذف" },
  "team.view": { en: "View", ar: "عرض" },
  "team.active": { en: "Active", ar: "نشط" },
  "team.inactive": { en: "Inactive", ar: "غير نشط" },
  "team.online": { en: "Online", ar: "متصل" },
  "team.offline": { en: "Offline", ar: "غير متصل" },
  "team.all": { en: "All", ar: "الكل" },

  // Students Module
  "stu.title": { en: "Students", ar: "الطلاب" },
  "stu.overview": { en: "Overview", ar: "نظرة عامة" },
  "stu.allStudents": { en: "All Students", ar: "جميع الطلاب" },
  "stu.pods": { en: "Student Pods", ar: "مجموعات الطلاب" },
  "stu.progress": { en: "Progress", ar: "التقدم" },
  "stu.atRisk": { en: "At-Risk Students", ar: "طلاب في خطر" },
  "stu.wrongQuestions": { en: "Wrong Questions", ar: "أسئلة خاطئة" },
  "stu.memory": { en: "Memory & Weaknesses", ar: "الذاكرة ونقاط الضعف" },
  "stu.parents": { en: "Parent Center", ar: "مركز أولياء الأمور" },
  "stu.payments": { en: "Payments", ar: "المدفوعات" },
  "stu.certificates": { en: "Certificates", ar: "الشهادات" },
  "stu.reports": { en: "Reports", ar: "التقارير" },
  "stu.totalStudents": { en: "Total Students", ar: "إجمالي الطلاب" },
  "stu.activeThisWeek": { en: "Active This Week", ar: "نشطون هذا الأسبوع" },
  "stu.newEnrollments": { en: "New Enrollments", ar: "تسجيلات جديدة" },
  "stu.avgScore": { en: "Average Score", ar: "متوسط الدرجات" },
  "stu.completionRate": { en: "Completion Rate", ar: "معدل الإكمال" },
  "stu.totalRevenue": { en: "Total Revenue", ar: "إجمالي الإيرادات" },
  "stu.parentAlerts": { en: "Parent Alerts", ar: "تنبيهات أولياء الأمور" },
  "stu.recentActivity": { en: "Recent Student Activity", ar: "نشاط الطلاب الأخير" },
  "stu.topProgress": { en: "Top Progress Students", ar: "أفضل الطلاب تقدماً" },
  "stu.addStudent": { en: "Add Student", ar: "إضافة طالب" },
  "stu.assignAssistant": { en: "Assign Assistant", ar: "تعيين مساعد" },
  "stu.contactParent": { en: "Contact Parent", ar: "تواصل مع ولي الأمر" },
  "stu.exportReport": { en: "Export Report", ar: "تصدير تقرير" },
  "stu.name": { en: "Name", ar: "الاسم" },
  "stu.grade": { en: "Grade", ar: "الصف" },
  "stu.courses": { en: "Courses", ar: "الدورات" },
  "stu.riskLevel": { en: "Risk Level", ar: "مستوى الخطر" },
  "stu.lastLogin": { en: "Last Login", ar: "آخر دخول" },
  "stu.assistantTeacher": { en: "Assistant Teacher", ar: "المعلم المساعد" },
  "stu.parentContact": { en: "Parent Contact", ar: "تواصل ولي الأمر" },
  "stu.noLogin": { en: "No Login", ar: "لم يسجل دخول" },
  "stu.missingHW": { en: "Missing Homework", ar: "واجبات مفقودة" },
  "stu.fallingGrades": { en: "Falling Grades", ar: "درجات متراجعة" },
  "stu.lowCompletion": { en: "Low Completion", ar: "إكمال منخفض" },
  "stu.failedQuizzes": { en: "Failed Quizzes", ar: "اختبارات راسب" },
  "stu.notifyParent": { en: "Notify Parent", ar: "إبلاغ ولي الأمر" },
  "stu.createRevisionPlan": { en: "Create Revision Plan", ar: "إنشاء خطة مراجعة" },
  "stu.escalate": { en: "Escalate", ar: "تصعيد" },
  "stu.concept": { en: "Concept", ar: "مفهوم" },
  "stu.atomicConcept": { en: "Atomic Concept", ar: "مفهوم ذري" },
  "stu.retryCount": { en: "Retry Count", ar: "عدد المحاولات" },
  "stu.assignPractice": { en: "Assign Practice", ar: "تعيين تمرين" },
  "stu.printSheet": { en: "Print Sheet", ar: "طباعة ورقة" },
  "stu.sendRevision": { en: "Send Revision Task", ar: "إرسال مهمة مراجعة" },
  "stu.strengths": { en: "Strengths", ar: "نقاط القوة" },
  "stu.weakConcepts": { en: "Weak Concepts", ar: "مفاهيم ضعيفة" },
  "stu.forgettingCurve": { en: "Forgetting Curve", ar: "منحنى النسيان" },
  "stu.attentionPattern": { en: "Attention Pattern", ar: "نمط الانتباه" },
  "stu.recommendations": { en: "Recommendations", ar: "التوصيات" },
  "stu.longTermInsights": { en: "Long-term Insights", ar: "رؤى طويلة المدى" },
  "stu.parentName": { en: "Parent Name", ar: "اسم ولي الأمر" },
  "stu.relation": { en: "Relation", ar: "العلاقة" },
  "stu.lastContact": { en: "Last Contact", ar: "آخر تواصل" },
  "stu.alertStatus": { en: "Alert Status", ar: "حالة التنبيه" },
  "stu.sendWeeklyReport": { en: "Send Weekly Report", ar: "إرسال تقرير أسبوعي" },
  "stu.scheduleCall": { en: "Schedule Call", ar: "جدولة مكالمة" },
  "stu.walletBalance": { en: "Wallet Balance", ar: "رصيد المحفظة" },
  "stu.coupon": { en: "Coupon", ar: "كوبون" },
  "stu.refundStatus": { en: "Refund Status", ar: "حالة الاسترداد" },
  "stu.issuedDate": { en: "Issued Date", ar: "تاريخ الإصدار" },
  "stu.download": { en: "Download", ar: "تحميل" },
  "stu.revoke": { en: "Revoke", ar: "سحب" },
  "stu.exportPDF": { en: "Export PDF", ar: "تصدير PDF" },
  "stu.exportExcel": { en: "Export Excel", ar: "تصدير Excel" },
  "stu.high": { en: "High", ar: "عالي" },
  "stu.medium": { en: "Medium", ar: "متوسط" },
  "stu.low": { en: "Low", ar: "منخفض" },
  "stu.none": { en: "None", ar: "لا يوجد" },
  "stu.active": { en: "Active", ar: "نشط" },
  "stu.inactive": { en: "Inactive", ar: "غير نشط" },
  "stu.new": { en: "New", ar: "جديد" },

  // Assessment Module
  "assess.title": { en: "Assessment", ar: "التقييم" },
  "assess.overview": { en: "Overview", ar: "نظرة عامة" },
  "assess.gradingQueue": { en: "Grading Queue", ar: "قائمة التصحيح" },
  "assess.manualGrading": { en: "Manual Grading", ar: "تصحيح يدوي" },
  "assess.submissions": { en: "Submissions", ar: "التسليمات" },
  "assess.results": { en: "Results", ar: "النتائج" },
  "assess.gradebook": { en: "Gradebook", ar: "سجل الدرجات" },
  "assess.analytics": { en: "Analytics", ar: "التحليلات" },
  "assess.academicIntegrity": { en: "Academic Integrity", ar: "النزاهة الأكاديمية" },
  "assess.pendingSubs": { en: "Pending Submissions", ar: "تسليمات معلقة" },
  "assess.essaysToGrade": { en: "Essays to Grade", ar: "مقالات للتصحيح" },
  "assess.hwToReview": { en: "Homework to Review", ar: "واجبات للمراجعة" },
  "assess.fileUploads": { en: "File Uploads", ar: "ملفات مرفوعة" },
  "assess.avgScore": { en: "Average Score", ar: "متوسط الدرجات" },
  "assess.passRate": { en: "Pass Rate", ar: "معدل النجاح" },
  "assess.suspiciousAttempts": { en: "Suspicious Attempts", ar: "محاولات مشبوهة" },
  "assess.gradedToday": { en: "Graded Today", ar: "صُحح اليوم" },
  "assess.essays": { en: "Essays", ar: "المقالات" },
  "assess.homework": { en: "Homework", ar: "الواجبات" },
  "assess.manualReview": { en: "Manual Review", ar: "مراجعة يدوية" },
  "assess.student": { en: "Student", ar: "الطالب" },
  "assess.course": { en: "Course", ar: "الدورة" },
  "assess.assessment": { en: "Assessment", ar: "التقييم" },
  "assess.type": { en: "Type", ar: "النوع" },
  "assess.submittedAt": { en: "Submitted At", ar: "تاريخ التسليم" },
  "assess.assignedTo": { en: "Assigned To", ar: "معيّن لـ" },
  "assess.priority": { en: "Priority", ar: "الأولوية" },
  "assess.gradeAction": { en: "Grade", ar: "تصحيح" },
  "assess.assignToAssistant": { en: "Assign to Assistant", ar: "تعيين لمساعد" },
  "assess.aiAssist": { en: "AI Assist", ar: "مساعدة ذكاء اصطناعي" },
  "assess.returnForRevision": { en: "Return for Revision", ar: "إرجاع للمراجعة" },
  "assess.searchStudent": { en: "Search Student", ar: "بحث عن طالب" },
  "assess.scoreInput": { en: "Score", ar: "الدرجة" },
  "assess.feedback": { en: "Feedback", ar: "ملاحظات" },
  "assess.rubric": { en: "Rubric", ar: "معايير التقييم" },
  "assess.saveGrade": { en: "Save Grade", ar: "حفظ الدرجة" },
  "assess.score": { en: "Score", ar: "الدرجة" },
  "assess.attempts": { en: "Attempts", ar: "المحاولات" },
  "assess.grader": { en: "Grader", ar: "المصحح" },
  "assess.scoreRange": { en: "Score Range", ar: "نطاق الدرجات" },
  "assess.quizResults": { en: "Quiz Results", ar: "نتائج الاختبارات" },
  "assess.examResults": { en: "Exam Results", ar: "نتائج الامتحانات" },
  "assess.hwResults": { en: "Homework Results", ar: "نتائج الواجبات" },
  "assess.topStudents": { en: "Top Students", ar: "أفضل الطلاب" },
  "assess.failedStudents": { en: "Failed Students", ar: "طلاب راسبون" },
  "assess.rank": { en: "Rank", ar: "الترتيب" },
  "assess.completion": { en: "Completion", ar: "الإكمال" },
  "assess.average": { en: "Average", ar: "المتوسط" },
  "assess.exportExcel": { en: "Export Excel", ar: "تصدير Excel" },
  "assess.exportPDF": { en: "Export PDF", ar: "تصدير PDF" },
  "assess.questionDifficulty": { en: "Question Difficulty", ar: "صعوبة الأسئلة" },
  "assess.bestSessions": { en: "Best Performing Sessions", ar: "أفضل الجلسات أداءً" },
  "assess.needSupport": { en: "Students Needing Support", ar: "طلاب بحاجة لدعم" },
  "assess.multiDevice": { en: "Multiple Device Warnings", ar: "تنبيهات أجهزة متعددة" },
  "assess.tabSwitch": { en: "Tab Switch Events", ar: "أحداث تبديل التبويب" },
  "assess.timeAnomalies": { en: "Time Anomalies", ar: "شذوذ زمني" },
  "assess.ipChanges": { en: "IP/Device Changes", ar: "تغيّر الجهاز/IP" },
  "assess.flaggedStudents": { en: "Flagged Students", ar: "طلاب مُعلَّمون" },
  "assess.clearFlag": { en: "Clear Flag", ar: "إزالة العلامة" },
  "assess.reviewAction": { en: "Review", ar: "مراجعة" },
  "assess.pending": { en: "Pending", ar: "معلق" },
  "assess.graded": { en: "Graded", ar: "مُصحَّح" },
  "assess.returned": { en: "Returned", ar: "مُعاد" },
  "assess.all": { en: "All", ar: "الكل" },

  // Business Module
  "biz.title": { en: "Business", ar: "الأعمال" },
  "biz.revenueWallet": { en: "Revenue & Wallet", ar: "الإيرادات والمحفظة" },
  "biz.sales": { en: "Sales", ar: "المبيعات" },
  "biz.orders": { en: "Orders", ar: "الطلبات" },
  "biz.studentPayments": { en: "Students Payments", ar: "مدفوعات الطلاب" },
  "biz.couponsPricing": { en: "Coupons & Pricing", ar: "الكوبونات والتسعير" },
  "biz.subscriptions": { en: "Subscriptions", ar: "الاشتراكات" },
  "biz.revenueSharing": { en: "Revenue Sharing", ar: "توزيع الأرباح" },
  "biz.payouts": { en: "Payouts", ar: "التحويلات" },
  "biz.expenses": { en: "Expenses", ar: "المصروفات" },
  "biz.rewards": { en: "Rewards", ar: "المكافآت" },
  "biz.financialReports": { en: "Financial Reports", ar: "التقارير المالية" },
  "biz.taxesInvoices": { en: "Taxes & Invoices", ar: "الضرائب والفواتير" },
  "biz.marketing": { en: "Marketing", ar: "التسويق" },
  "biz.todayRevenue": { en: "Today Revenue", ar: "إيرادات اليوم" },
  "biz.monthlyRevenue": { en: "Monthly Revenue", ar: "الإيرادات الشهرية" },
  "biz.pendingRevenue": { en: "Pending Revenue", ar: "إيرادات معلقة" },
  "biz.availableBalance": { en: "Available Balance", ar: "الرصيد المتاح" },
  "biz.withdrawable": { en: "Withdrawable", ar: "قابل للسحب" },
  "biz.refunds": { en: "Refunds", ar: "المستردات" },
  "biz.netProfit": { en: "Net Profit", ar: "صافي الربح" },
  "biz.pending": { en: "Pending", ar: "معلق" },
  "biz.paid": { en: "Paid", ar: "مدفوع" },
  "biz.failed": { en: "Failed", ar: "فشل" },
  "biz.refunded": { en: "Refunded", ar: "مسترد" },
  "biz.cancelled": { en: "Cancelled", ar: "ملغي" },
  "biz.approve": { en: "Approve", ar: "موافقة" },
  "biz.refund": { en: "Refund", ar: "استرداد" },
  "biz.extendAccess": { en: "Extend Access", ar: "تمديد الوصول" },
  "biz.createCoupon": { en: "Create Coupon", ar: "إنشاء كوبون" },
  "biz.monthly": { en: "Monthly", ar: "شهري" },
  "biz.quarterly": { en: "Quarterly", ar: "ربع سنوي" },
  "biz.yearly": { en: "Yearly", ar: "سنوي" },
  "biz.custom": { en: "Custom", ar: "مخصص" },
  "biz.activeSubs": { en: "Active Subscribers", ar: "مشتركون نشطون" },
  "biz.expiredSubs": { en: "Expired Subscribers", ar: "مشتركون منتهون" },
  "biz.salaries": { en: "Salaries", ar: "الرواتب" },
  "biz.ads": { en: "Ads", ar: "الإعلانات" },
  "biz.campaigns": { en: "Campaigns", ar: "الحملات" },
  "biz.leads": { en: "Leads", ar: "العملاء المحتملون" },
  "biz.conversionRate": { en: "Conversion Rate", ar: "معدل التحويل" },
  "biz.visitors": { en: "Visitors", ar: "الزوار" },
  "biz.exportPDF": { en: "Export PDF", ar: "تصدير PDF" },
  "biz.exportExcel": { en: "Export Excel", ar: "تصدير Excel" },

  // Insights Module
  "ins.title": { en: "Insights", ar: "الرؤى" },
  "ins.overview": { en: "Overview", ar: "نظرة عامة" },
  "ins.courseAnalytics": { en: "Course Analytics", ar: "تحليلات الدورات" },
  "ins.studentAnalytics": { en: "Student Analytics", ar: "تحليلات الطلاب" },
  "ins.assessmentAnalytics": { en: "Assessment Analytics", ar: "تحليلات التقييم" },
  "ins.conceptAnalytics": { en: "Concept Analytics", ar: "تحليلات المفاهيم" },
  "ins.memoryInsights": { en: "Memory Insights", ar: "رؤى الذاكرة" },
  "ins.revenueAnalytics": { en: "Revenue Analytics", ar: "تحليلات الإيرادات" },
  "ins.aiInsights": { en: "AI Insights", ar: "رؤى الذكاء الاصطناعي" },
  "ins.predictions": { en: "Predictions", ar: "التنبؤات" },
  "ins.reportsCenter": { en: "Reports Center", ar: "مركز التقارير" },
  "ins.generatorStudio": { en: "Generator Studio", ar: "استوديو التوليد" },
  "ins.totalStudents": { en: "Total Students", ar: "إجمالي الطلاب" },
  "ins.growthRate": { en: "Growth Rate", ar: "معدل النمو" },
  "ins.enrollment": { en: "Enrollment", ar: "التسجيل" },
  "ins.completion": { en: "Completion", ar: "الإكمال" },
  "ins.watchTime": { en: "Watch Time", ar: "وقت المشاهدة" },
  "ins.dropOff": { en: "Drop-off Points", ar: "نقاط الانقطاع" },
  "ins.highPerformers": { en: "High Performers", ar: "الأداء العالي" },
  "ins.coverage": { en: "Coverage", ar: "التغطية" },
  "ins.mastery": { en: "Mastery", ar: "الإتقان" },
  "ins.retention": { en: "Retention", ar: "الاحتفاظ" },
  "ins.forgettingCurve": { en: "Forgetting Curves", ar: "منحنيات النسيان" },
  "ins.roi": { en: "ROI", ar: "العائد على الاستثمار" },
  "ins.churn": { en: "Churn", ar: "التسرب" },
  "ins.weeklyReport": { en: "Weekly Report", ar: "تقرير أسبوعي" },
  "ins.monthlyReport": { en: "Monthly Report", ar: "تقرير شهري" },
  "ins.questionGen": { en: "Question Generator", ar: "مولد الأسئلة" },
  "ins.quizGen": { en: "Quiz Generator", ar: "مولد الاختبارات" },
  "ins.homeworkGen": { en: "Homework Generator", ar: "مولد الواجبات" },
  "ins.examGen": { en: "Exam Generator", ar: "مولد الامتحانات" },
  "ins.notesGen": { en: "Notes Generator", ar: "مولد الملاحظات" },
  "ins.sessionGen": { en: "Session Generator", ar: "مولد الحصص" },
  "ins.pptGen": { en: "PPT Generator", ar: "مولد العروض" },
  "ins.pdfGen": { en: "PDF Generator", ar: "مولد PDF" },
  "ins.revisionGen": { en: "Revision Generator", ar: "مولد المراجعات" },
  "ins.certGen": { en: "Certificate Generator", ar: "مولد الشهادات" },

  // Parent Module
  "parent.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "parent.settings": { en: "Settings", ar: "الإعدادات" },
  "parent.selectChild": { en: "Select Child", ar: "اختر الطفل" },
  "parent.exportPDF": { en: "Export PDF", ar: "تصدير PDF" },
  "parent.contactTeacher": { en: "Contact Teacher", ar: "تواصل مع المعلم" },
  "parent.payNow": { en: "Pay Now", ar: "ادفع الآن" },
  "parent.overallStatus": { en: "Overall Status", ar: "الحالة العامة" },
  "parent.courseProgress": { en: "Course Progress", ar: "تقدم الدورة" },
  "parent.avgScore": { en: "Average Score", ar: "متوسط الدرجات" },
  "parent.attendance": { en: "Attendance", ar: "الحضور" },
  "parent.missingHW": { en: "Missing Homework", ar: "واجبات مفقودة" },
  "parent.upcomingExams": { en: "Upcoming Exams", ar: "امتحانات قادمة" },
  "parent.paymentStatus": { en: "Payment Status", ar: "حالة الدفع" },
  "parent.excellent": { en: "Excellent", ar: "ممتاز" },
  "parent.stable": { en: "Stable", ar: "مستقر" },
  "parent.needsAttention": { en: "Needs Attention", ar: "يحتاج اهتمام" },
  "parent.critical": { en: "Critical", ar: "حرج" },
  "parent.smartInsight": { en: "Smart Parent Insight", ar: "رؤية ذكية لولي الأمر" },
  "parent.progress": { en: "Progress", ar: "التقدم" },
  "parent.assessments": { en: "Assessments", ar: "التقييمات" },
  "parent.alerts": { en: "Alerts", ar: "التنبيهات" },
  "parent.weaknesses": { en: "Areas to Improve", ar: "مجالات التحسين" },
  "parent.payments": { en: "Payments", ar: "المدفوعات" },
  "parent.communication": { en: "Communication", ar: "التواصل" },
  "parent.timeline": { en: "Activity Timeline", ar: "الجدول الزمني" },
  "parent.present": { en: "Present", ar: "حاضر" },
  "parent.absent": { en: "Absent", ar: "غائب" },
  "parent.late": { en: "Late", ar: "متأخر" },
  "parent.warning": { en: "Warning", ar: "تحذير" },
  "parent.info": { en: "Info", ar: "معلومة" },
  "parent.positive": { en: "Positive", ar: "إيجابي" },
  "parent.sendMessage": { en: "Send Message", ar: "إرسال رسالة" },
  "parent.walletBalance": { en: "Wallet Balance", ar: "رصيد المحفظة" },
  "parent.downloadInvoice": { en: "Download Invoice", ar: "تحميل الفاتورة" },
  "parent.printReport": { en: "Print Report", ar: "طباعة التقرير" },
  "parent.weeklyTrend": { en: "Weekly Trend", ar: "الاتجاه الأسبوعي" },
  "parent.enrolledCourses": { en: "Enrolled Courses", ar: "الدورات المسجلة" },
  "parent.lastActivity": { en: "Last Activity", ar: "آخر نشاط" },
  "parent.watchTime": { en: "Watch Time", ar: "وقت المشاهدة" },
  "parent.recentQuizzes": { en: "Recent Quizzes", ar: "اختبارات حديثة" },
  "parent.homeworkStatus": { en: "Homework Status", ar: "حالة الواجبات" },
  "parent.examResults": { en: "Exam Results", ar: "نتائج الامتحانات" },
  "parent.teacherMessages": { en: "Teacher Messages", ar: "رسائل المعلم" },
  "parent.assistantNotes": { en: "Assistant Notes", ar: "ملاحظات المساعد" },
};

const translate = (key: string, lang: Lang) => {
  const direct = dict[key]?.[lang];
  if (direct) return direct;
  const byEnglish = Object.values(dict).find((entry) => entry.en === key);
  return byEnglish?.[lang] ?? key;
};

const getStoredTheme = (): Theme => {
  if (typeof window === "undefined") return "dark";
  const stored = window.localStorage.getItem("classz-theme");
  return stored === "light" || stored === "dark" ? stored : "dark";
};

const getStoredLang = (): Lang => {
  if (typeof window === "undefined") return "en";
  const stored = window.localStorage.getItem("classz-lang");
  return stored === "ar" || stored === "en" ? stored : "en";
};

export function AppProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>(getStoredTheme);
  const [lang, setLangState] = useState<Lang>(getStoredLang);

  useEffect(() => {
    const root = document.documentElement;
    root.classList.toggle("dark", theme === "dark");
    localStorage.setItem("classz-theme", theme);
  }, [theme]);

  useEffect(() => {
    const root = document.documentElement;
    const nextDir = lang === "ar" ? "rtl" : "ltr";
    root.setAttribute("dir", nextDir);
    root.setAttribute("lang", lang);
    root.dataset.lang = lang;
    root.dataset.dir = nextDir;
    document.body.setAttribute("dir", nextDir);
    document.body.setAttribute("lang", lang);
    localStorage.setItem("classz-lang", lang);
  }, [lang]);

  const value: AppState = {
    theme,
    setTheme: setThemeState,
    toggleTheme: () => setThemeState((p) => (p === "dark" ? "light" : "dark")),
    lang,
    setLang: setLangState,
    toggleLang: () => setLangState((p) => (p === "en" ? "ar" : "en")),
    dir: lang === "ar" ? "rtl" : "ltr",
    t: (key) => translate(key, lang),
  };

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error("useApp must be used within AppProvider");
  return ctx;
}
