import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

type Theme = "light" | "dark" | "game";
type Lang = "en" | "ar";

interface AppState {
  theme: Theme;
  toggleTheme: () => void;
  setTheme: (t: Theme) => void;
  uiSoundsEnabled: boolean;
  toggleUiSounds: () => void;
  setUiSoundsEnabled: (enabled: boolean) => void;
  cinematicLoginMotionEnabled: boolean;
  toggleCinematicLoginMotion: () => void;
  setCinematicLoginMotionEnabled: (enabled: boolean) => void;
  lang: Lang;
  setLang: (l: Lang) => void;
  toggleLang: () => void;
  dir: "ltr" | "rtl";
  t: (key: string, params?: Record<string, string | number>) => string;
}

const AppContext = createContext<AppState | null>(null);

const dict: Record<string, { en: string; ar: string }> = {
  "student.upcomingEvents": { en: "Upcoming Events", ar: "الأحداث القادمة" },
  "student.dontMissAnything": { en: "Don't miss anything", ar: "لا تفوّت أي شيء" },
  "student.achievements": { en: "Achievements", ar: "الإنجازات" },
  "student.keepItUp": { en: "You're doing great! Keep it up!", ar: "أداؤك رائع! واصل التقدم!" },
  "student.dayStreak": { en: "Day Streak", ar: "سلسلة الأيام" },
  "student.totalXp": { en: "Total XP", ar: "إجمالي نقاط الخبرة" },
  "student.weeklyRank": { en: "Weekly Rank", ar: "الترتيب الأسبوعي" },
  "student.badgesEarned": { en: "Badges Earned", ar: "الشارات المكتسبة" },
  "student.bestSubject": { en: "Best Subject", ar: "أفضل مادة" },
  "student.awards": { en: "Awards", ar: "الجوائز" },
  "student.subjectDistribution": { en: "Subject Distribution", ar: "توزيع المواد" },
  "student.scoreAcrossSubjects": { en: "Your score across subjects", ar: "درجاتك عبر المواد" },
  "student.aiCoach": { en: "AI Coach", ar: "المدرب الذكي" },
  "student.personalStudyCoach": { en: "Your personal study coach", ar: "مدربك الشخصي للدراسة" },
  "student.buildStudyPlan": { en: "Build Study Plan", ar: "أنشئ خطة دراسة" },
  "student.generateQuiz": { en: "Generate Quiz", ar: "أنشئ اختبارًا" },
  "student.explainWeakPoints": { en: "Explain Weak Points", ar: "اشرح نقاط الضعف" },
  "student.reviewDueLessons": { en: "Review Due Lessons", ar: "راجع الدروس المستحقة" },
  "student.askAnything": { en: "Ask Anything", ar: "اسأل أي شيء" },
  "nav.home": { en: "Home", ar: "الرئيسية" },
  "nav.about": { en: "About", ar: "من نحن" },
  "nav.courses": { en: "Courses", ar: "الدورات" },
  "nav.pricing": { en: "Pricing", ar: "الأسعار" },
  "nav.contact": { en: "Contact", ar: "تواصل" },
  "nav.login": { en: "Login", ar: "تسجيل الدخول" },
  "nav.register": { en: "Register", ar: "إنشاء حساب" },
  "nav.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "nav.learning": { en: "Learning", ar: "التعلم" },
  "nav.practice": { en: "Practice", ar: "التدريب" },
  "nav.rewards": { en: "Rewards", ar: "المكافآت" },
  "nav.more": { en: "More", ar: "المزيد" },
  "nav.communication": { en: "Communication", ar: "التواصل" },
  "role.student": { en: "Student", ar: "طالب" },
  "role.studentTagline": { en: "Learn & grow", ar: "تعلّم وتقدّم" },
  "role.teacher": { en: "Teacher", ar: "معلم" },
  "role.teacherTagline": { en: "Your academy workspace", ar: "مساحة عمل الأكاديمية" },
  "student.smartRevision": { en: "Smart Revision", ar: "مراجعة ذكية" },
  "student.myNotes": { en: "My Notes", ar: "ملاحظاتي" },
  "student.progress": { en: "Progress", ar: "التقدم" },
  "student.assignments": { en: "Assignments", ar: "الواجبات" },
  "student.questionBank": { en: "Question Bank", ar: "بنك الأسئلة" },
  "student.wrongQuestions": { en: "Wrong Questions", ar: "الأسئلة الخاطئة" },
  "student.trophyRoom": { en: "Trophy Room", ar: "غرفة الإنجازات" },
  "student.leaderboard": { en: "Leaderboard", ar: "لوحة الصدارة" },
  "student.certificates": { en: "Certificates", ar: "الشهادات" },
  "student.wallet": { en: "Wallet", ar: "المحفظة" },
  "student.aiAssistant": { en: "AI Assistant", ar: "المساعد الذكي" },
  "student.notifications": { en: "Notifications", ar: "الإشعارات" },
  "student.goodEvening": { en: "Good evening", ar: "مساء الخير" },
  "student.dashboardSubtitle": { en: "Ready to crush your goals today!", ar: "جاهز لتحقيق أهدافك اليوم!" },
  "student.dailyMissions": { en: "Daily Missions", ar: "مهام اليوم" },
  "student.complete": { en: "complete", ar: "مكتملة" },
  "student.continueWhereLeftOff": { en: "Continue where you left off", ar: "تابع من حيث توقفت" },
  "student.noCoursesYet": { en: "No courses yet", ar: "لا توجد دورات بعد" },
  "student.learningAdventureStarts": { en: "Your learning adventure starts here.", ar: "تبدأ رحلة التعلم من هنا." },
  "student.browseCourses": { en: "Browse Courses", ar: "تصفح الدورات" },
  "teacher.workspaceTitle": { en: "Teacher Workspace", ar: "مساحة عمل المعلم" },
  "teacher.thisWeek": { en: "this week", ar: "هذا الأسبوع" },
  "teacher.createSession": { en: "Create Session", ar: "إنشاء حصة" },
  "teacher.addQuiz": { en: "Add Quiz", ar: "إضافة اختبار" },
  "teacher.uploadMaterial": { en: "Upload Material", ar: "رفع مادة" },
  "teacher.addQuestions": { en: "Add Questions", ar: "إضافة أسئلة" },
  "teacher.announcement": { en: "Announcement", ar: "إعلان" },
  "teacher.viewRevenue": { en: "View Revenue", ar: "عرض الإيرادات" },
  "teacher.essayGradingQueue": { en: "Essay Grading Queue", ar: "قائمة تصحيح المقالات" },
  "teacher.recentSales": { en: "Recent Sales", ar: "آخر المبيعات" },
  "teacher.paymentId": { en: "Payment ID", ar: "رقم الدفع" },
  "teacher.item": { en: "Item", ar: "العنصر" },
  "teacher.date": { en: "Date", ar: "التاريخ" },
  "teacher.activeCourses": { en: "Active Courses", ar: "الدورات النشطة" },
  "teacher.teamMessages": { en: "Team Messages", ar: "رسائل الفريق" },
  "teacher.unread": { en: "unread", ar: "غير مقروءة" },
  "teacher.activeSessions": { en: "Active Sessions", ar: "الحصص النشطة" },
  "Must Do Today": { en: "Must Do Today", ar: "يجب إنجازه اليوم" },
  "Recommended": { en: "Recommended", ar: "موصى به" },
  "Optional": { en: "Optional", ar: "اختياري" },
  "(if you have time)": { en: "(if you have time)", ar: "(إذا كان لديك وقت)" },
  "Today's Mission": { en: "Today's Mission", ar: "مهمة اليوم" },
  "What will you achieve today?": { en: "What will you achieve today?", ar: "ماذا ستحقق اليوم؟" },
  "Start Today": { en: "Start Today", ar: "ابدأ اليوم" },
  "Discipline today": { en: "Discipline today", ar: "انضباط اليوم" },
  "Success tomorrow": { en: "Success tomorrow", ar: "نجاح الغد" },
  "Resume": { en: "Resume", ar: "استئناف" },
  "Weak Points": { en: "Weak Points", ar: "نقاط الضعف" },
  "Focus on what matters": { en: "Focus on what matters", ar: "ركّز على الأهم" },
  "High": { en: "High", ar: "عالٍ" },
  "Medium": { en: "Medium", ar: "متوسط" },
  "Low": { en: "Low", ar: "منخفض" },
  "Revision Due": { en: "Revision Due", ar: "مراجعة مستحقة" },
  "Based on memory system": { en: "Based on memory system", ar: "حسب نظام الذاكرة" },
  "Due today": { en: "Due today", ar: "مستحق اليوم" },
  "In 1 day": { en: "In 1 day", ar: "خلال يوم" },
  "Attention Needed": { en: "Attention Needed", ar: "بحاجة إلى انتباه" },
  "Important updates": { en: "Important updates", ar: "تحديثات مهمة" },
  "Overdue": { en: "Overdue", ar: "متأخر" },
  "Due tomorrow": { en: "Due tomorrow", ar: "مستحق غدًا" },
  "Favorite Course": { en: "Favorite Course", ar: "الدورة المفضلة" },
  "Your most studied this week": { en: "Your most studied this week", ar: "الأكثر دراسة هذا الأسبوع" },
  "Hours this week": { en: "Hours this week", ar: "ساعات هذا الأسبوع" },
  "Lessons completed": { en: "Lessons completed", ar: "دروس مكتملة" },
  "Continue Learning": { en: "Continue Learning", ar: "متابعة التعلم" },
  "hero.title": { en: "Learn Smarter with CLASSZ", ar: "تعلّم بذكاء مع CLASSZ" },
  "hero.subtitle": {
    en: "A premium learning platform that blends structured courses, gamified progress, and an AI study assistant for secondary students and teachers.",
    ar: "منصة تعليمية متميزة تجمع بين الدورات المنظمة والتقدم التفاعلي ومساعد ذكاء اصطناعي للطلاب والمعلمين.",
  },
  "hero.getStarted": { en: "Get started free", ar: "ابدأ مجانًا" },
  "common.search": { en: "Search", ar: "بحث" },
  "common.globalSearchPlaceholder": { en: "Search courses, lessons, students…", ar: "ابحث في الدورات والدروس والطلاب…" },
  "common.viewAll": { en: "View all", ar: "عرض الكل" },
  "common.logout": { en: "Log out", ar: "تسجيل الخروج" },
  "common.settings": { en: "Settings", ar: "الإعدادات" },
  "workspace.title": { en: "Workspace", ar: "مساحة العمل" },
  "workspace.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "workspace.myCourses": { en: "My Courses", ar: "دوراتي" },
  "workspace.contentStudio": { en: "Content Studio", ar: "استوديو المحتوى" },

  // Team Module
  "team.title": { en: "Team", ar: "الفريق" },
  "team.overview": { en: "Overview", ar: "نظرة عامة" },
  "team.members": { en: "Members", ar: "الأعضاء" },
  "team.recruitment": { en: "Recruitment", ar: "التوظيف" },
  "team.applications": { en: "Applications", ar: "الطلبات" },
  "team.roles": { en: "Roles & Permissions", ar: "الأدوار والصلاحيات" },
  "team.studentPods": { en: "Student Pods", ar: "مجموعات الطلاب" },
  "team.revenueSharing": { en: "Revenue Sharing", ar: "توزيع الأرباح" },
  "team.tasks": { en: "Tasks & Workflow", ar: "المهام وسير العمل" },
  "team.activityLogs": { en: "Activity Logs", ar: "سجل النشاط" },
  "team.invitations": { en: "Invitations", ar: "الدعوات" },
  "team.management": { en: "Team Management", ar: "إدارة الفريق" },
  "team.subtitle": { en: "Manage your academy staff and permissions", ar: "إدارة موظفي الأكاديمية والصلاحيات" },
  "team.totalMembers": { en: "Total Members", ar: "إجمالي الأعضاء" },
  "team.teachers": { en: "Teachers", ar: "المعلمون" },
  "team.assistantTeachers": { en: "Assistant Teachers", ar: "المعلمون المساعدون" },
  "team.contentManagers": { en: "Content Managers", ar: "مديرو المحتوى" },
  "team.finance": { en: "Finance", ar: "المالية" },
  "team.support": { en: "Support", ar: "الدعم" },
  "team.pendingInvitations": { en: "Pending Invitations", ar: "الدعوات المعلقة" },
  "team.recentActivity": { en: "Recent Activity", ar: "النشاط الأخير" },
  "team.quickActions": { en: "Quick Actions", ar: "إجراءات سريعة" },
  "team.addMember": { en: "Add Member", ar: "إضافة عضو" },
  "team.publishRecruitment": { en: "Publish Recruitment Post", ar: "نشر إعلان توظيف" },
  "team.reviewApplications": { en: "Review Applications", ar: "مراجعة الطلبات" },
  "team.assignStudents": { en: "Assign Students to Assistant", ar: "تعيين طلاب لمساعد" },
  "team.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "team.mobile": { en: "Mobile", ar: "الجوال" },
  "team.email": { en: "Email", ar: "البريد الإلكتروني" },
  "team.role": { en: "Role", ar: "الدور" },
  "team.assignedCourses": { en: "Assigned Courses", ar: "الدورات المعيّنة" },
  "team.username": { en: "Username", ar: "اسم المستخدم" },
  "team.password": { en: "Password", ar: "كلمة المرور" },
  "team.autoGenerate": { en: "Auto-generate", ar: "توليد تلقائي" },
  "team.sendCredentials": { en: "Send Credentials", ar: "إرسال بيانات الدخول" },
  "team.viaWhatsApp": { en: "Via WhatsApp", ar: "عبر واتساب" },
  "team.viaEmail": { en: "Via Email", ar: "عبر البريد" },
  "team.copyCredentials": { en: "Copy Credentials", ar: "نسخ البيانات" },
  "team.personalInfo": { en: "Personal Info", ar: "المعلومات الشخصية" },
  "team.permissions": { en: "Permissions", ar: "الصلاحيات" },
  "team.revenueShare": { en: "Revenue Share", ar: "حصة الأرباح" },
  "team.activityStats": { en: "Activity Stats", ar: "إحصائيات النشاط" },
  "team.status": { en: "Status", ar: "الحالة" },
  "team.lastActive": { en: "Last Active", ar: "آخر نشاط" },
  "team.actions": { en: "Actions", ar: "الإجراءات" },
  "team.jobTitle": { en: "Job Title", ar: "عنوان الوظيفة" },
  "team.jobType": { en: "Job Type", ar: "نوع الوظيفة" },
  "team.salaryType": { en: "Salary Type", ar: "نوع الراتب" },
  "team.salaryAmount": { en: "Salary Amount", ar: "قيمة الراتب" },
  "team.requirements": { en: "Requirements", ar: "المتطلبات" },
  "team.responsibilities": { en: "Responsibilities", ar: "المسؤوليات" },
  "team.experience": { en: "Required Experience", ar: "الخبرة المطلوبة" },
  "team.publish": { en: "Publish", ar: "نشر" },
  "team.draft": { en: "Draft", ar: "مسودة" },
  "team.applicantName": { en: "Applicant Name", ar: "اسم المتقدم" },
  "team.position": { en: "Position", ar: "الوظيفة" },
  "team.submittedDate": { en: "Submitted Date", ar: "تاريخ التقديم" },
  "team.new": { en: "New", ar: "جديد" },
  "team.shortlisted": { en: "Shortlisted", ar: "قائمة مختصرة" },
  "team.interview": { en: "Interview", ar: "مقابلة" },
  "team.accepted": { en: "Accepted", ar: "مقبول" },
  "team.rejected": { en: "Rejected", ar: "مرفوض" },
  "team.reject": { en: "Reject", ar: "رفض" },
  "team.shortlist": { en: "Shortlist", ar: "قائمة مختصرة" },
  "team.moveToInterview": { en: "Move to Interview", ar: "نقل للمقابلة" },
  "team.accept": { en: "Accept", ar: "قبول" },
  "team.createAccount": { en: "Create Team Account", ar: "إنشاء حساب الفريق" },
  "team.accountCreated": { en: "Account Created", ar: "تم إنشاء الحساب" },
  "team.cv": { en: "CV", ar: "السيرة الذاتية" },
  "team.introVideo": { en: "Intro Video", ar: "فيديو تعريفي" },
  "team.notes": { en: "Notes", ar: "ملاحظات" },
  "team.evaluationScore": { en: "Evaluation Score", ar: "درجة التقييم" },
  "team.customRole": { en: "Custom Role", ar: "دور مخصص" },
  "team.permissionMatrix": { en: "Permission Matrix", ar: "مصفوفة الصلاحيات" },
  "team.uploadMaterials": { en: "Upload Materials", ar: "رفع المواد" },
  "team.manageSessions": { en: "Manage Sessions", ar: "إدارة الحصص" },
  "team.createQuestions": { en: "Create Questions", ar: "إنشاء أسئلة" },
  "team.createQuizzes": { en: "Create Quizzes", ar: "إنشاء اختبارات" },
  "team.createHomework": { en: "Create Homework", ar: "إنشاء واجبات" },
  "team.createExams": { en: "Create Exams", ar: "إنشاء امتحانات" },
  "team.gradeEssays": { en: "Grade Essays", ar: "تصحيح المقالات" },
  "team.replyStudents": { en: "Reply to Students", ar: "الرد على الطلاب" },
  "team.contactParents": { en: "Contact Parents", ar: "التواصل مع أولياء الأمور" },
  "team.viewAnalytics": { en: "View Analytics", ar: "عرض التحليلات" },
  "team.managePayments": { en: "Manage Payments", ar: "إدارة المدفوعات" },
  "team.manageTeam": { en: "Manage Team", ar: "إدارة الفريق" },
  "team.manageSettings": { en: "Manage Settings", ar: "إدارة الإعدادات" },
  "team.teacher": { en: "Teacher", ar: "المعلم" },
  "team.assistantTeacher": { en: "Assistant Teacher", ar: "معلم مساعد" },
  "team.contentManager": { en: "Content Manager", ar: "مدير محتوى" },
  "team.moderator": { en: "Moderator", ar: "مشرف" },
  "team.developer": { en: "Developer", ar: "مطور" },
  "team.admin": { en: "Admin", ar: "مسؤول" },
  "team.groupName": { en: "Group Name", ar: "اسم المجموعة" },
  "team.studentCount": { en: "Number of Students", ar: "عدد الطلاب" },
  "team.riskSummary": { en: "Risk Summary", ar: "ملخص المخاطر" },
  "team.completionAvg": { en: "Completion Average", ar: "متوسط الإنجاز" },
  "team.unsubmittedHW": { en: "Unsubmitted Homework", ar: "واجبات لم تُسلّم" },
  "team.autoDistribute": { en: "Automatic Distribution", ar: "توزيع تلقائي" },
  "team.manualAssign": { en: "Manual Assignment", ar: "تعيين يدوي" },
  "team.fixedSalary": { en: "Fixed Salary", ar: "راتب ثابت" },
  "team.percentageShare": { en: "Percentage Share", ar: "حصة نسبية" },
  "team.perTask": { en: "Per Task", ar: "لكل مهمة" },
  "team.perGraded": { en: "Per Graded Assignment", ar: "لكل واجب مصحح" },
  "team.totalEarned": { en: "Total Earned", ar: "إجمالي المكتسب" },
  "team.paid": { en: "Paid", ar: "مدفوع" },
  "team.pending": { en: "Pending", ar: "معلق" },
  "team.todo": { en: "To Do", ar: "قيد الانتظار" },
  "team.inProgress": { en: "In Progress", ar: "قيد التنفيذ" },
  "team.review": { en: "Review", ar: "مراجعة" },
  "team.done": { en: "Done", ar: "تم" },
  "team.priority": { en: "Priority", ar: "الأولوية" },
  "team.dueDate": { en: "Due Date", ar: "تاريخ الاستحقاق" },
  "team.high": { en: "High", ar: "عالية" },
  "team.medium": { en: "Medium", ar: "متوسطة" },
  "team.low": { en: "Low", ar: "منخفضة" },
  "team.filterByMember": { en: "Filter by Member", ar: "تصفية حسب العضو" },
  "team.filterByAction": { en: "Filter by Action", ar: "تصفية حسب الإجراء" },
  "team.filterByDate": { en: "Filter by Date", ar: "تصفية حسب التاريخ" },
  "team.filterByCourse": { en: "Filter by Course", ar: "تصفية حسب الدورة" },
  "team.sentDate": { en: "Sent Date", ar: "تاريخ الإرسال" },
  "team.expiryDate": { en: "Expiry Date", ar: "تاريخ الانتهاء" },
  "team.expired": { en: "Expired", ar: "منتهي" },
  "team.revoked": { en: "Revoked", ar: "ملغي" },
  "team.resend": { en: "Resend", ar: "إعادة إرسال" },
  "team.revoke": { en: "Revoke", ar: "إلغاء" },
  "team.amount": { en: "Amount", ar: "المبلغ" },
  "team.compensationType": { en: "Compensation Type", ar: "نوع التعويض" },
  "team.save": { en: "Save", ar: "حفظ" },
  "team.cancel": { en: "Cancel", ar: "إلغاء" },
  "team.close": { en: "Close", ar: "إغلاق" },
  "team.edit": { en: "Edit", ar: "تعديل" },
  "team.delete": { en: "Delete", ar: "حذف" },
  "team.view": { en: "View", ar: "عرض" },
  "team.active": { en: "Active", ar: "نشط" },
  "team.inactive": { en: "Inactive", ar: "غير نشط" },
  "team.online": { en: "Online", ar: "متصل" },
  "team.offline": { en: "Offline", ar: "غير متصل" },
  "team.all": { en: "All", ar: "الكل" },

  // Students Module
  "stu.title": { en: "Students", ar: "الطلاب" },
  "stu.overview": { en: "Overview", ar: "نظرة عامة" },
  "stu.allStudents": { en: "All Students", ar: "جميع الطلاب" },
  "stu.pods": { en: "Student Pods", ar: "مجموعات الطلاب" },
  "stu.progress": { en: "Progress", ar: "التقدم" },
  "stu.atRisk": { en: "At-Risk Students", ar: "طلاب في خطر" },
  "stu.wrongQuestions": { en: "Wrong Questions", ar: "أسئلة خاطئة" },
  "stu.memory": { en: "Memory & Weaknesses", ar: "الذاكرة ونقاط الضعف" },
  "stu.parents": { en: "Parent Center", ar: "مركز أولياء الأمور" },
  "stu.payments": { en: "Payments", ar: "المدفوعات" },
  "stu.certificates": { en: "Certificates", ar: "الشهادات" },
  "stu.reports": { en: "Reports", ar: "التقارير" },
  "stu.totalStudents": { en: "Total Students", ar: "إجمالي الطلاب" },
  "stu.activeThisWeek": { en: "Active This Week", ar: "نشطون هذا الأسبوع" },
  "stu.newEnrollments": { en: "New Enrollments", ar: "تسجيلات جديدة" },
  "stu.avgScore": { en: "Average Score", ar: "متوسط الدرجات" },
  "stu.completionRate": { en: "Completion Rate", ar: "معدل الإكمال" },
  "stu.totalRevenue": { en: "Total Revenue", ar: "إجمالي الإيرادات" },
  "stu.parentAlerts": { en: "Parent Alerts", ar: "تنبيهات أولياء الأمور" },
  "stu.recentActivity": { en: "Recent Student Activity", ar: "نشاط الطلاب الأخير" },
  "stu.topProgress": { en: "Top Progress Students", ar: "أفضل الطلاب تقدماً" },
  "stu.addStudent": { en: "Add Student", ar: "إضافة طالب" },
  "stu.assignAssistant": { en: "Assign Assistant", ar: "تعيين مساعد" },
  "stu.contactParent": { en: "Contact Parent", ar: "تواصل مع ولي الأمر" },
  "stu.exportReport": { en: "Export Report", ar: "تصدير تقرير" },
  "stu.name": { en: "Name", ar: "الاسم" },
  "stu.grade": { en: "Grade", ar: "الصف" },
  "stu.courses": { en: "Courses", ar: "الدورات" },
  "stu.riskLevel": { en: "Risk Level", ar: "مستوى الخطر" },
  "stu.lastLogin": { en: "Last Login", ar: "آخر دخول" },
  "stu.assistantTeacher": { en: "Assistant Teacher", ar: "المعلم المساعد" },
  "stu.parentContact": { en: "Parent Contact", ar: "تواصل ولي الأمر" },
  "stu.noLogin": { en: "No Login", ar: "لم يسجل دخول" },
  "stu.missingHW": { en: "Missing Homework", ar: "واجبات مفقودة" },
  "stu.fallingGrades": { en: "Falling Grades", ar: "درجات متراجعة" },
  "stu.lowCompletion": { en: "Low Completion", ar: "إكمال منخفض" },
  "stu.failedQuizzes": { en: "Failed Quizzes", ar: "اختبارات راسب" },
  "stu.notifyParent": { en: "Notify Parent", ar: "إبلاغ ولي الأمر" },
  "stu.createRevisionPlan": { en: "Create Revision Plan", ar: "إنشاء خطة مراجعة" },
  "stu.escalate": { en: "Escalate", ar: "تصعيد" },
  "stu.concept": { en: "Concept", ar: "مفهوم" },
  "stu.atomicConcept": { en: "Atomic Concept", ar: "مفهوم ذري" },
  "stu.retryCount": { en: "Retry Count", ar: "عدد المحاولات" },
  "stu.assignPractice": { en: "Assign Practice", ar: "تعيين تمرين" },
  "stu.printSheet": { en: "Print Sheet", ar: "طباعة ورقة" },
  "stu.sendRevision": { en: "Send Revision Task", ar: "إرسال مهمة مراجعة" },
  "stu.strengths": { en: "Strengths", ar: "نقاط القوة" },
  "stu.weakConcepts": { en: "Weak Concepts", ar: "مفاهيم ضعيفة" },
  "stu.forgettingCurve": { en: "Forgetting Curve", ar: "منحنى النسيان" },
  "stu.attentionPattern": { en: "Attention Pattern", ar: "نمط الانتباه" },
  "stu.recommendations": { en: "Recommendations", ar: "التوصيات" },
  "stu.longTermInsights": { en: "Long-term Insights", ar: "رؤى طويلة المدى" },
  "stu.parentName": { en: "Parent Name", ar: "اسم ولي الأمر" },
  "stu.relation": { en: "Relation", ar: "العلاقة" },
  "stu.lastContact": { en: "Last Contact", ar: "آخر تواصل" },
  "stu.alertStatus": { en: "Alert Status", ar: "حالة التنبيه" },
  "stu.sendWeeklyReport": { en: "Send Weekly Report", ar: "إرسال تقرير أسبوعي" },
  "stu.scheduleCall": { en: "Schedule Call", ar: "جدولة مكالمة" },
  "stu.walletBalance": { en: "Wallet Balance", ar: "رصيد المحفظة" },
  "stu.coupon": { en: "Coupon", ar: "كوبون" },
  "stu.refundStatus": { en: "Refund Status", ar: "حالة الاسترداد" },
  "stu.issuedDate": { en: "Issued Date", ar: "تاريخ الإصدار" },
  "stu.download": { en: "Download", ar: "تحميل" },
  "stu.revoke": { en: "Revoke", ar: "سحب" },
  "stu.exportPDF": { en: "Export PDF", ar: "تصدير PDF" },
  "stu.exportExcel": { en: "Export Excel", ar: "تصدير Excel" },
  "stu.high": { en: "High", ar: "عالي" },
  "stu.medium": { en: "Medium", ar: "متوسط" },
  "stu.low": { en: "Low", ar: "منخفض" },
  "stu.none": { en: "None", ar: "لا يوجد" },
  "stu.active": { en: "Active", ar: "نشط" },
  "stu.inactive": { en: "Inactive", ar: "غير نشط" },
  "stu.new": { en: "New", ar: "جديد" },

  // Assessment Module
  "assess.title": { en: "Assessment", ar: "التقييم" },
  "assess.overview": { en: "Overview", ar: "نظرة عامة" },
  "assess.assignments": { en: "Assignments", ar: "الواجبات" },
  "assess.gradingQueue": { en: "Grading Queue", ar: "قائمة التصحيح" },
  "assess.manualGrading": { en: "Manual Grading", ar: "تصحيح يدوي" },
  "assess.submissions": { en: "Submissions", ar: "التسليمات" },
  "assess.results": { en: "Results", ar: "النتائج" },
  "assess.gradebook": { en: "Gradebook", ar: "سجل الدرجات" },
  "assess.analytics": { en: "Analytics", ar: "التحليلات" },
  "assess.academicIntegrity": { en: "Academic Integrity", ar: "النزاهة الأكاديمية" },
  "assess.pendingSubs": { en: "Pending Submissions", ar: "تسليمات معلقة" },
  "assess.essaysToGrade": { en: "Essays to Grade", ar: "مقالات للتصحيح" },
  "assess.hwToReview": { en: "Homework to Review", ar: "واجبات للمراجعة" },
  "assess.fileUploads": { en: "File Uploads", ar: "ملفات مرفوعة" },
  "assess.avgScore": { en: "Average Score", ar: "متوسط الدرجات" },
  "assess.passRate": { en: "Pass Rate", ar: "معدل النجاح" },
  "assess.suspiciousAttempts": { en: "Suspicious Attempts", ar: "محاولات مشبوهة" },
  "assess.gradedToday": { en: "Graded Today", ar: "صُحح اليوم" },
  "assess.essays": { en: "Essays", ar: "المقالات" },
  "assess.homework": { en: "Homework", ar: "الواجبات" },
  "assess.manualReview": { en: "Manual Review", ar: "مراجعة يدوية" },
  "assess.student": { en: "Student", ar: "الطالب" },
  "assess.course": { en: "Course", ar: "الدورة" },
  "assess.assessment": { en: "Assessment", ar: "التقييم" },
  "assess.type": { en: "Type", ar: "النوع" },
  "assess.submittedAt": { en: "Submitted At", ar: "تاريخ التسليم" },
  "assess.assignedTo": { en: "Assigned To", ar: "معيّن لـ" },
  "assess.priority": { en: "Priority", ar: "الأولوية" },
  "assess.gradeAction": { en: "Grade", ar: "تصحيح" },
  "assess.assignToAssistant": { en: "Assign to Assistant", ar: "تعيين لمساعد" },
  "assess.aiAssist": { en: "AI Assist", ar: "مساعدة ذكاء اصطناعي" },
  "assess.returnForRevision": { en: "Return for Revision", ar: "إرجاع للمراجعة" },
  "assess.searchStudent": { en: "Search Student", ar: "بحث عن طالب" },
  "assess.scoreInput": { en: "Score", ar: "الدرجة" },
  "assess.feedback": { en: "Feedback", ar: "ملاحظات" },
  "assess.rubric": { en: "Rubric", ar: "معايير التقييم" },
  "assess.saveGrade": { en: "Save Grade", ar: "حفظ الدرجة" },
  "assess.score": { en: "Score", ar: "الدرجة" },
  "assess.attempts": { en: "Attempts", ar: "المحاولات" },
  "assess.grader": { en: "Grader", ar: "المصحح" },
  "assess.scoreRange": { en: "Score Range", ar: "نطاق الدرجات" },
  "assess.quizResults": { en: "Quiz Results", ar: "نتائج الاختبارات" },
  "assess.examResults": { en: "Exam Results", ar: "نتائج الامتحانات" },
  "assess.hwResults": { en: "Homework Results", ar: "نتائج الواجبات" },
  "assess.topStudents": { en: "Top Students", ar: "أفضل الطلاب" },
  "assess.failedStudents": { en: "Failed Students", ar: "طلاب راسبون" },
  "assess.rank": { en: "Rank", ar: "الترتيب" },
  "assess.completion": { en: "Completion", ar: "الإكمال" },
  "assess.average": { en: "Average", ar: "المتوسط" },
  "assess.exportExcel": { en: "Export Excel", ar: "تصدير Excel" },
  "assess.exportPDF": { en: "Export PDF", ar: "تصدير PDF" },
  "assess.questionDifficulty": { en: "Question Difficulty", ar: "صعوبة الأسئلة" },
  "assess.bestSessions": { en: "Best Performing Sessions", ar: "أفضل الجلسات أداءً" },
  "assess.needSupport": { en: "Students Needing Support", ar: "طلاب بحاجة لدعم" },
  "assess.multiDevice": { en: "Multiple Device Warnings", ar: "تنبيهات أجهزة متعددة" },
  "assess.tabSwitch": { en: "Tab Switch Events", ar: "أحداث تبديل التبويب" },
  "assess.timeAnomalies": { en: "Time Anomalies", ar: "شذوذ زمني" },
  "assess.ipChanges": { en: "IP/Device Changes", ar: "تغيّر الجهاز/IP" },
  "assess.flaggedStudents": { en: "Flagged Students", ar: "طلاب مُعلَّمون" },
  "assess.clearFlag": { en: "Clear Flag", ar: "إزالة العلامة" },
  "assess.reviewAction": { en: "Review", ar: "مراجعة" },
  "assess.pending": { en: "Pending", ar: "معلق" },
  "assess.graded": { en: "Graded", ar: "مُصحَّح" },
  "assess.returned": { en: "Returned", ar: "مُعاد" },
  "assess.all": { en: "All", ar: "الكل" },

  // Business Module
  "biz.title": { en: "Business", ar: "الأعمال" },
  "biz.revenueWallet": { en: "Revenue & Wallet", ar: "الإيرادات والمحفظة" },
  "biz.sales": { en: "Sales", ar: "المبيعات" },
  "biz.orders": { en: "Orders", ar: "الطلبات" },
  "biz.studentPayments": { en: "Students Payments", ar: "مدفوعات الطلاب" },
  "biz.couponsPricing": { en: "Coupons & Pricing", ar: "الكوبونات والتسعير" },
  "biz.subscriptions": { en: "Subscriptions", ar: "الاشتراكات" },
  "biz.revenueSharing": { en: "Revenue Sharing", ar: "توزيع الأرباح" },
  "biz.payouts": { en: "Payouts", ar: "التحويلات" },
  "biz.expenses": { en: "Expenses", ar: "المصروفات" },
  "biz.rewards": { en: "Rewards", ar: "المكافآت" },
  "biz.financialReports": { en: "Financial Reports", ar: "التقارير المالية" },
  "biz.taxesInvoices": { en: "Taxes & Invoices", ar: "الضرائب والفواتير" },
  "biz.marketing": { en: "Marketing", ar: "التسويق" },
  "biz.todayRevenue": { en: "Today Revenue", ar: "إيرادات اليوم" },
  "biz.monthlyRevenue": { en: "Monthly Revenue", ar: "الإيرادات الشهرية" },
  "biz.pendingRevenue": { en: "Pending Revenue", ar: "إيرادات معلقة" },
  "biz.availableBalance": { en: "Available Balance", ar: "الرصيد المتاح" },
  "biz.withdrawable": { en: "Withdrawable", ar: "قابل للسحب" },
  "biz.refunds": { en: "Refunds", ar: "المستردات" },
  "biz.netProfit": { en: "Net Profit", ar: "صافي الربح" },
  "biz.pending": { en: "Pending", ar: "معلق" },
  "biz.paid": { en: "Paid", ar: "مدفوع" },
  "biz.failed": { en: "Failed", ar: "فشل" },
  "biz.refunded": { en: "Refunded", ar: "مسترد" },
  "biz.cancelled": { en: "Cancelled", ar: "ملغي" },
  "biz.approve": { en: "Approve", ar: "موافقة" },
  "biz.refund": { en: "Refund", ar: "استرداد" },
  "biz.extendAccess": { en: "Extend Access", ar: "تمديد الوصول" },
  "biz.createCoupon": { en: "Create Coupon", ar: "إنشاء كوبون" },
  "biz.monthly": { en: "Monthly", ar: "شهري" },
  "biz.quarterly": { en: "Quarterly", ar: "ربع سنوي" },
  "biz.yearly": { en: "Yearly", ar: "سنوي" },
  "biz.custom": { en: "Custom", ar: "مخصص" },
  "biz.activeSubs": { en: "Active Subscribers", ar: "مشتركون نشطون" },
  "biz.expiredSubs": { en: "Expired Subscribers", ar: "مشتركون منتهون" },
  "biz.salaries": { en: "Salaries", ar: "الرواتب" },
  "biz.ads": { en: "Ads", ar: "الإعلانات" },
  "biz.campaigns": { en: "Campaigns", ar: "الحملات" },
  "biz.leads": { en: "Leads", ar: "العملاء المحتملون" },
  "biz.conversionRate": { en: "Conversion Rate", ar: "معدل التحويل" },
  "biz.visitors": { en: "Visitors", ar: "الزوار" },
  "biz.exportPDF": { en: "Export PDF", ar: "تصدير PDF" },
  "biz.exportExcel": { en: "Export Excel", ar: "تصدير Excel" },

  // Insights Module
  "ins.title": { en: "Insights", ar: "الرؤى" },
  "ins.overview": { en: "Overview", ar: "نظرة عامة" },
  "ins.courseAnalytics": { en: "Course Analytics", ar: "تحليلات الدورات" },
  "ins.studentAnalytics": { en: "Student Analytics", ar: "تحليلات الطلاب" },
  "ins.assessmentAnalytics": { en: "Assessment Analytics", ar: "تحليلات التقييم" },
  "ins.conceptAnalytics": { en: "Concept Analytics", ar: "تحليلات المفاهيم" },
  "ins.memoryInsights": { en: "Memory Insights", ar: "رؤى الذاكرة" },
  "ins.revenueAnalytics": { en: "Revenue Analytics", ar: "تحليلات الإيرادات" },
  "ins.aiInsights": { en: "AI Insights", ar: "رؤى الذكاء الاصطناعي" },
  "ins.predictions": { en: "Predictions", ar: "التنبؤات" },
  "ins.reportsCenter": { en: "Reports Center", ar: "مركز التقارير" },
  "ins.generatorStudio": { en: "Generator Studio", ar: "استوديو التوليد" },
  "ins.totalStudents": { en: "Total Students", ar: "إجمالي الطلاب" },
  "ins.growthRate": { en: "Growth Rate", ar: "معدل النمو" },
  "ins.enrollment": { en: "Enrollment", ar: "التسجيل" },
  "ins.completion": { en: "Completion", ar: "الإكمال" },
  "ins.watchTime": { en: "Watch Time", ar: "وقت المشاهدة" },
  "ins.dropOff": { en: "Drop-off Points", ar: "نقاط الانقطاع" },
  "ins.highPerformers": { en: "High Performers", ar: "الأداء العالي" },
  "ins.coverage": { en: "Coverage", ar: "التغطية" },
  "ins.mastery": { en: "Mastery", ar: "الإتقان" },
  "ins.retention": { en: "Retention", ar: "الاحتفاظ" },
  "ins.forgettingCurve": { en: "Forgetting Curves", ar: "منحنيات النسيان" },
  "ins.roi": { en: "ROI", ar: "العائد على الاستثمار" },
  "ins.churn": { en: "Churn", ar: "التسرب" },
  "ins.weeklyReport": { en: "Weekly Report", ar: "تقرير أسبوعي" },
  "ins.monthlyReport": { en: "Monthly Report", ar: "تقرير شهري" },
  "ins.questionGen": { en: "Question Generator", ar: "مولد الأسئلة" },
  "ins.quizGen": { en: "Quiz Generator", ar: "مولد الاختبارات" },
  "ins.homeworkGen": { en: "Homework Generator", ar: "مولد الواجبات" },
  "ins.examGen": { en: "Exam Generator", ar: "مولد الامتحانات" },
  "ins.notesGen": { en: "Notes Generator", ar: "مولد الملاحظات" },
  "ins.sessionGen": { en: "Session Generator", ar: "مولد الحصص" },
  "ins.pptGen": { en: "PPT Generator", ar: "مولد العروض" },
  "ins.pdfGen": { en: "PDF Generator", ar: "مولد PDF" },
  "ins.revisionGen": { en: "Revision Generator", ar: "مولد المراجعات" },
  "ins.certGen": { en: "Certificate Generator", ar: "مولد الشهادات" },

  // Parent Module
  "parent.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "parent.settings": { en: "Settings", ar: "الإعدادات" },
  "parent.selectChild": { en: "Select Child", ar: "اختر الطفل" },
  "parent.exportPDF": { en: "Export PDF", ar: "تصدير PDF" },
  "parent.contactTeacher": { en: "Contact Teacher", ar: "تواصل مع المعلم" },
  "parent.payNow": { en: "Pay Now", ar: "ادفع الآن" },
  "parent.overallStatus": { en: "Overall Status", ar: "الحالة العامة" },
  "parent.courseProgress": { en: "Course Progress", ar: "تقدم الدورة" },
  "parent.avgScore": { en: "Average Score", ar: "متوسط الدرجات" },
  "parent.attendance": { en: "Attendance", ar: "الحضور" },
  "parent.missingHW": { en: "Missing Homework", ar: "واجبات مفقودة" },
  "parent.upcomingExams": { en: "Upcoming Exams", ar: "امتحانات قادمة" },
  "parent.paymentStatus": { en: "Payment Status", ar: "حالة الدفع" },
  "parent.excellent": { en: "Excellent", ar: "ممتاز" },
  "parent.stable": { en: "Stable", ar: "مستقر" },
  "parent.needsAttention": { en: "Needs Attention", ar: "يحتاج اهتمام" },
  "parent.critical": { en: "Critical", ar: "حرج" },
  "parent.smartInsight": { en: "Smart Parent Insight", ar: "رؤية ذكية لولي الأمر" },
  "parent.progress": { en: "Progress", ar: "التقدم" },
  "parent.assessments": { en: "Assessments", ar: "التقييمات" },
  "parent.alerts": { en: "Alerts", ar: "التنبيهات" },
  "parent.weaknesses": { en: "Areas to Improve", ar: "مجالات التحسين" },
  "parent.payments": { en: "Payments", ar: "المدفوعات" },
  "parent.communication": { en: "Communication", ar: "التواصل" },
  "parent.timeline": { en: "Activity Timeline", ar: "الجدول الزمني" },
  "parent.present": { en: "Present", ar: "حاضر" },
  "parent.absent": { en: "Absent", ar: "غائب" },
  "parent.late": { en: "Late", ar: "متأخر" },
  "parent.warning": { en: "Warning", ar: "تحذير" },
  "parent.info": { en: "Info", ar: "معلومة" },
  "parent.positive": { en: "Positive", ar: "إيجابي" },
  "parent.sendMessage": { en: "Send Message", ar: "إرسال رسالة" },
  "parent.walletBalance": { en: "Wallet Balance", ar: "رصيد المحفظة" },
  "parent.downloadInvoice": { en: "Download Invoice", ar: "تحميل الفاتورة" },
  "parent.printReport": { en: "Print Report", ar: "طباعة التقرير" },
  "parent.weeklyTrend": { en: "Weekly Trend", ar: "الاتجاه الأسبوعي" },
  "parent.enrolledCourses": { en: "Enrolled Courses", ar: "الدورات المسجلة" },
  "parent.lastActivity": { en: "Last Activity", ar: "آخر نشاط" },
  "parent.watchTime": { en: "Watch Time", ar: "وقت المشاهدة" },
  "parent.recentQuizzes": { en: "Recent Quizzes", ar: "اختبارات حديثة" },
  "parent.homeworkStatus": { en: "Homework Status", ar: "حالة الواجبات" },
  "parent.examResults": { en: "Exam Results", ar: "نتائج الامتحانات" },
  "parent.teacherMessages": { en: "Teacher Messages", ar: "رسائل المعلم" },
  "parent.assistantNotes": { en: "Assistant Notes", ar: "ملاحظات المساعد" },

  // SuperAdmin Module
  "sa.platform": { en: "Platform", ar: "المنصة" },
  "sa.platformFinance": { en: "Platform Finance", ar: "مالية المنصة" },
  "sa.operations": { en: "Operations", ar: "العمليات" },
  "sa.system": { en: "System", ar: "النظام" },
  "sa.overview": { en: "Overview", ar: "نظرة عامة" },
  "sa.academies": { en: "Academies", ar: "الأكاديميات" },
  "sa.teachers": { en: "Teachers", ar: "المعلمون" },
  "sa.students": { en: "Students", ar: "الطلاب" },
  "sa.courses": { en: "Courses", ar: "الدورات" },
  "sa.support": { en: "Support", ar: "الدعم" },
  "sa.tickets": { en: "Tickets", ar: "التذاكر" },
  "sa.reports": { en: "Reports", ar: "التقارير" },
  "sa.systemHealth": { en: "System Health", ar: "صحة النظام" },
  "sa.announcements": { en: "Announcements", ar: "الإعلانات" },
  "sa.rolesPermissions": { en: "Roles & Permissions", ar: "الأدوار والصلاحيات" },
  "sa.adminUsers": { en: "Admin Users", ar: "مستخدمو الإدارة" },
  "sa.settings": { en: "Settings", ar: "الإعدادات" },
  "sa.security": { en: "Security", ar: "الأمان" },
  "sa.auditLogs": { en: "Audit Logs", ar: "سجل المراجعة" },

  // Platform Finance Module
  "pf.overview": { en: "Finance Overview", ar: "نظرة عامة مالية" },
  "pf.overviewSubtitle": { en: "CLASSZ platform-wide financial health", ar: "الوضع المالي العام لمنصة CLASSZ" },
  "pf.transactions": { en: "Transactions", ar: "المعاملات" },
  "pf.transactionsSubtitle": { en: "All platform transactions across academies", ar: "جميع معاملات المنصة عبر الأكاديميات" },
  "pf.teacherRevenue": { en: "Teacher Revenue", ar: "إيرادات المعلمين" },
  "pf.teacherRevenueSubtitle": { en: "Revenue breakdown per teacher", ar: "تفصيل الإيرادات لكل معلم" },
  "pf.platformRevenue": { en: "Platform Revenue", ar: "إيرادات المنصة" },
  "pf.platformRevenueSubtitle": { en: "CLASSZ revenue sources and trends", ar: "مصادر واتجاهات إيرادات CLASSZ" },
  "pf.withdrawals": { en: "Withdrawals", ar: "السحوبات" },
  "pf.withdrawalsSubtitle": { en: "Teacher withdrawal requests & payouts", ar: "طلبات سحب المعلمين والتحويلات" },
  "pf.subscriptions": { en: "Subscriptions", ar: "الاشتراكات" },
  "pf.subscriptionsSubtitle": { en: "Teacher subscription plans & metrics", ar: "خطط اشتراك المعلمين والمقاييس" },
  "pf.invoices": { en: "Invoices", ar: "الفواتير" },
  "pf.invoicesSubtitle": { en: "Platform, teacher & student invoices", ar: "فواتير المنصة والمعلمين والطلاب" },
  "pf.expenses": { en: "Expenses", ar: "المصروفات" },
  "pf.expensesSubtitle": { en: "Platform operational expenses", ar: "مصروفات تشغيل المنصة" },
  "pf.affiliatePayouts": { en: "Affiliate Payouts", ar: "عمولات الشركاء" },
  "pf.affiliatePayoutsSubtitle": { en: "Affiliate commissions & payouts", ar: "عمولات ودفعات الشركاء" },
  "pf.taxes": { en: "Taxes", ar: "الضرائب" },
  "pf.taxesSubtitle": { en: "VAT, tax summary & reports", ar: "ضريبة القيمة المضافة والملخص والتقارير" },
  "pf.financialReports": { en: "Financial Reports", ar: "التقارير المالية" },
  "pf.financialReportsSubtitle": { en: "Generate & export financial reports", ar: "إنشاء وتصدير التقارير المالية" },
  "pf.financialAuditLogs": { en: "Financial Audit Logs", ar: "سجل المراجعة المالية" },
  "pf.financialAuditLogsSubtitle": { en: "Timeline of all financial actions", ar: "الجدول الزمني لجميع الإجراءات المالية" },
  "pf.gmv": { en: "GMV", ar: "إجمالي قيمة البضائع" },
  "pf.platformRevenueCard": { en: "Platform Revenue", ar: "إيرادات المنصة" },
  "pf.pendingWithdrawals": { en: "Pending Withdrawals", ar: "سحوبات معلقة" },
  "pf.monthlyGrowth": { en: "Monthly Growth", ar: "النمو الشهري" },
  "pf.activeSubscriptions": { en: "Active Subscriptions", ar: "اشتراكات نشطة" },
  "pf.refunds": { en: "Refunds", ar: "المستردات" },
  "pf.expenses2": { en: "Expenses", ar: "المصروفات" },
  "pf.netProfit": { en: "Net Profit", ar: "صافي الربح" },
  "pf.revenueTrend": { en: "Revenue Trend", ar: "اتجاه الإيرادات" },
  "pf.platformFeeDistribution": { en: "Platform Fee Distribution", ar: "توزيع رسوم المنصة" },
  "pf.topEarningTeachers": { en: "Top Earning Teachers", ar: "أعلى المعلمين إيراداً" },
  "pf.pendingWithdrawalPreview": { en: "Pending Withdrawals Preview", ar: "معاينة السحوبات المعلقة" },
  "pf.recentFinancialActivity": { en: "Recent Financial Activity", ar: "النشاط المالي الأخير" },
  "pf.date": { en: "Date", ar: "التاريخ" },
  "pf.teacher": { en: "Teacher", ar: "المعلم" },
  "pf.academy": { en: "Academy", ar: "الأكاديمية" },
  "pf.student": { en: "Student", ar: "الطالب" },
  "pf.product": { en: "Product", ar: "المنتج" },
  "pf.amount": { en: "Amount", ar: "المبلغ" },
  "pf.platformFee": { en: "Platform Fee", ar: "رسوم المنصة" },
  "pf.netTeacherAmount": { en: "Net Teacher Amount", ar: "صافي المعلم" },
  "pf.paymentMethod": { en: "Payment Method", ar: "طريقة الدفع" },
  "pf.status": { en: "Status", ar: "الحالة" },
  "pf.grossRevenue": { en: "Gross Revenue", ar: "الإيرادات الإجمالية" },
  "pf.netRevenue": { en: "Net Revenue", ar: "صافي الإيرادات" },
  "pf.pendingBalance": { en: "Pending Balance", ar: "الرصيد المعلق" },
  "pf.paidBalance": { en: "Paid Balance", ar: "الرصيد المدفوع" },
  "pf.method": { en: "Method", ar: "الطريقة" },
  "pf.requestedAt": { en: "Requested At", ar: "تاريخ الطلب" },
  "pf.riskFlag": { en: "Risk Flag", ar: "علامة الخطر" },
  "pf.approvedBy": { en: "Approved By", ar: "موافقة من" },
  "pf.plan": { en: "Plan", ar: "الخطة" },
  "pf.monthlyFee": { en: "Monthly Fee", ar: "الرسوم الشهرية" },
  "pf.renewalDate": { en: "Renewal Date", ar: "تاريخ التجديد" },
  "pf.paymentStatus": { en: "Payment Status", ar: "حالة الدفع" },
  "pf.invoiceId": { en: "Invoice ID", ar: "رقم الفاتورة" },
  "pf.relatedUser": { en: "Related User", ar: "المستخدم المرتبط" },
  "pf.tax": { en: "Tax", ar: "الضريبة" },
  "pf.category": { en: "Category", ar: "الفئة" },
  "pf.description": { en: "Description", ar: "الوصف" },
  "pf.recurring": { en: "Recurring", ar: "متكرر" },
  "pf.affiliate": { en: "Affiliate", ar: "الشريك" },
  "pf.clicks": { en: "Clicks", ar: "النقرات" },
  "pf.leads": { en: "Leads", ar: "العملاء المحتملون" },
  "pf.sales": { en: "Sales", ar: "المبيعات" },
  "pf.commission": { en: "Commission", ar: "العمولة" },
  "pf.paid": { en: "Paid", ar: "مدفوع" },
  "pf.pending": { en: "Pending", ar: "معلق" },
  "pf.action": { en: "Action", ar: "الإجراء" },
  "pf.admin": { en: "Admin", ar: "المسؤول" },
  "pf.viewTransaction": { en: "View Transaction", ar: "عرض المعاملة" },
  "pf.refundMock": { en: "Refund", ar: "استرداد" },
  "pf.downloadReceipt": { en: "Download Receipt", ar: "تحميل الإيصال" },
  "pf.export": { en: "Export", ar: "تصدير" },
  "pf.viewWallet": { en: "View Wallet", ar: "عرض المحفظة" },
  "pf.viewTransactions": { en: "View Transactions", ar: "عرض المعاملات" },
  "pf.exportStatement": { en: "Export Statement", ar: "تصدير كشف حساب" },
  "pf.approve": { en: "Approve", ar: "موافقة" },
  "pf.reject": { en: "Reject", ar: "رفض" },
  "pf.markAsPaid": { en: "Mark as Paid", ar: "تعيين كمدفوع" },
  "pf.exportPayoutSheet": { en: "Export Payout Sheet", ar: "تصدير كشف المدفوعات" },
  "pf.downloadInvoice": { en: "Download Invoice", ar: "تحميل الفاتورة" },
  "pf.sendInvoice": { en: "Send Invoice", ar: "إرسال الفاتورة" },
  "pf.generateReceipt": { en: "Generate Receipt", ar: "إنشاء إيصال" },
  "pf.addExpense": { en: "Add Expense", ar: "إضافة مصروف" },
  "pf.editExpense": { en: "Edit Expense", ar: "تعديل المصروف" },
  "pf.exportExpenses": { en: "Export Expenses", ar: "تصدير المصروفات" },
  "pf.approvePayout": { en: "Approve Payout", ar: "موافقة على الدفع" },
  "pf.generateTaxReport": { en: "Generate Tax Report", ar: "إنشاء تقرير ضريبي" },
  "pf.downloadPDF": { en: "Download PDF", ar: "تحميل PDF" },
  "pf.exportExcel": { en: "Export Excel", ar: "تصدير Excel" },
  "pf.scheduleReport": { en: "Schedule Report", ar: "جدولة تقرير" },
  "pf.dateRange": { en: "Date Range", ar: "النطاق الزمني" },
  "pf.filterByTeacher": { en: "Filter by Teacher", ar: "تصفية حسب المعلم" },
  "pf.filterByAcademy": { en: "Filter by Academy", ar: "تصفية حسب الأكاديمية" },
  "pf.filterByStatus": { en: "Filter by Status", ar: "تصفية حسب الحالة" },
  "pf.filterByAction": { en: "Filter by Action", ar: "تصفية حسب الإجراء" },
  "pf.filterByAdmin": { en: "Filter by Admin", ar: "تصفية حسب المسؤول" },
  "pf.all": { en: "All", ar: "الكل" },
  "pf.completed": { en: "Completed", ar: "مكتمل" },
  "pf.failed": { en: "Failed", ar: "فشل" },
  "pf.refunded": { en: "Refunded", ar: "مسترد" },
  "pf.approved": { en: "Approved", ar: "موافق عليه" },
  "pf.rejected": { en: "Rejected", ar: "مرفوض" },
  "pf.active": { en: "Active", ar: "نشط" },
  "pf.expired": { en: "Expired", ar: "منتهي" },
  "pf.cancelled": { en: "Cancelled", ar: "ملغي" },
  "pf.trial": { en: "Trial", ar: "تجريبي" },
  "pf.overdue": { en: "Overdue", ar: "متأخر" },
  "pf.issued": { en: "Issued", ar: "صادر" },
  "pf.suspended": { en: "Suspended", ar: "موقوف" },
  "pf.pendingReview": { en: "Pending Review", ar: "قيد المراجعة" },
  "pf.platformFees": { en: "Platform Fees", ar: "رسوم المنصة" },
  "pf.teacherSubscriptions": { en: "Teacher Subscriptions", ar: "اشتراكات المعلمين" },
  "pf.adsRevenue": { en: "Ads Revenue", ar: "إيرادات الإعلانات" },
  "pf.affiliateRevenue": { en: "Affiliate Revenue", ar: "إيرادات الشركاء" },
  "pf.enterprisePlans": { en: "Enterprise Plans", ar: "خطط المؤسسات" },
  "pf.monthlyPlatformRevenue": { en: "Monthly Platform Revenue", ar: "الإيرادات الشهرية للمنصة" },
  "pf.revenueBySource": { en: "Revenue by Source", ar: "الإيرادات حسب المصدر" },
  "pf.platformFeeTrends": { en: "Platform Fee Trends", ar: "اتجاهات رسوم المنصة" },
  "pf.churn": { en: "Churn", ar: "معدل الإلغاء" },
  "pf.mrr": { en: "MRR", ar: "الإيراد الشهري المتكرر" },
  "pf.arr": { en: "ARR", ar: "الإيراد السنوي المتكرر" },
  "pf.upgrades": { en: "Upgrades", ar: "ترقيات" },
  "pf.downgrades": { en: "Downgrades", ar: "تخفيضات" },
  "pf.servers": { en: "Servers", ar: "الخوادم" },
  "pf.marketing": { en: "Marketing", ar: "التسويق" },
  "pf.employees": { en: "Employees", ar: "الموظفون" },
  "pf.supportCat": { en: "Support", ar: "الدعم" },
  "pf.tools": { en: "Tools", ar: "الأدوات" },
  "pf.legal": { en: "Legal", ar: "الشؤون القانونية" },
  "pf.paymentGateway": { en: "Payment Gateway", ar: "بوابة الدفع" },
  "pf.miscellaneous": { en: "Miscellaneous", ar: "متنوعات" },
  "pf.monthlyExpenses": { en: "Monthly Expenses", ar: "المصروفات الشهرية" },
  "pf.serverCosts": { en: "Server Costs", ar: "تكاليف الخوادم" },
  "pf.marketingSpend": { en: "Marketing Spend", ar: "إنفاق التسويق" },
  "pf.payroll": { en: "Payroll", ar: "الرواتب" },
  "pf.vatTaxSummary": { en: "VAT / Tax Summary", ar: "ملخص ضريبة القيمة المضافة" },
  "pf.taxableRevenue": { en: "Taxable Revenue", ar: "الإيرادات الخاضعة للضريبة" },
  "pf.deductibleExpenses": { en: "Deductible Expenses", ar: "المصروفات القابلة للخصم" },
  "pf.netTax": { en: "Net Tax", ar: "صافي الضريبة" },
  "pf.taxReports": { en: "Tax Reports", ar: "التقارير الضريبية" },
  "pf.gmvReport": { en: "GMV Report", ar: "تقرير إجمالي قيمة البضائع" },
  "pf.platformRevenueReport": { en: "Platform Revenue Report", ar: "تقرير إيرادات المنصة" },
  "pf.teacherRevenueReport": { en: "Teacher Revenue Report", ar: "تقرير إيرادات المعلمين" },
  "pf.withdrawalsReport": { en: "Withdrawals Report", ar: "تقرير السحوبات" },
  "pf.subscriptionsReport": { en: "Subscriptions Report", ar: "تقرير الاشتراكات" },
  "pf.expensesReport": { en: "Expenses Report", ar: "تقرير المصروفات" },
  "pf.profitReport": { en: "Profit Report", ar: "تقرير الأرباح" },
  "pf.taxReport": { en: "Tax Report", ar: "التقرير الضريبي" },
  "pf.none": { en: "None", ar: "لا يوجد" },
  "pf.low": { en: "Low", ar: "منخفض" },
  "pf.medium": { en: "Medium", ar: "متوسط" },
  "pf.high": { en: "High", ar: "عالي" },
  "pf.yes": { en: "Yes", ar: "نعم" },
  "pf.no": { en: "No", ar: "لا" },
  "pf.search": { en: "Search...", ar: "بحث..." },
  "pf.noResults": { en: "No results found.", ar: "لم يتم العثور على نتائج." },
  "pf.actionType": { en: "Action Type", ar: "نوع الإجراء" },
  "pf.selectReport": { en: "Select a report to generate", ar: "اختر تقريراً لإنشائه" },
  "pf.generateReport": { en: "Generate Report", ar: "إنشاء التقرير" },
  "pf.exportPDF": { en: "Export PDF", ar: "تصدير PDF" },
  "pf.source": { en: "Source", ar: "المصدر" },
  "pf.percentage": { en: "Percentage", ar: "النسبة" },
  "pf.fee": { en: "Fee", ar: "الرسوم" },
  "pf.revenue": { en: "Revenue", ar: "الإيرادات" },

  // SuperAdmin Lite additions
  "sa.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "sa.finance": { en: "Finance", ar: "المالية" },
  "sa.supportTickets": { en: "Support Tickets", ar: "تذاكر الدعم" },
  "sa.totalTeachers": { en: "Total Teachers", ar: "إجمالي المعلمين" },
  "sa.totalStudents": { en: "Total Students", ar: "إجمالي الطلاب" },
  "sa.totalRevenue": { en: "Total Revenue", ar: "إجمالي الإيرادات" },
  "sa.activeCourses": { en: "Active Courses", ar: "الدورات النشطة" },
  "sa.newRegistrations": { en: "New Registrations", ar: "التسجيلات الجديدة" },
  "sa.pendingWithdrawals": { en: "Pending Withdrawals", ar: "سحوبات معلقة" },
  "sa.monthlyGrowth": { en: "Monthly Growth", ar: "النمو الشهري" },
  "sa.activeAcademies": { en: "Active Academies", ar: "الأكاديميات النشطة" },
  "sa.topAcademies": { en: "Top Academies", ar: "أفضل الأكاديميات" },
  "sa.recentRegistrations": { en: "Recent Registrations", ar: "التسجيلات الأخيرة" },
  "sa.revenueTrend": { en: "Revenue Trend", ar: "اتجاه الإيرادات" },
  "sa.latestTickets": { en: "Latest Support Tickets", ar: "أحدث تذاكر الدعم" },
  "sa.recentActivity": { en: "Recent Activity", ar: "النشاط الأخير" },
  "sa.searchAcademy": { en: "Search academy...", ar: "بحث عن أكاديمية..." },
  "sa.name": { en: "Name", ar: "الاسم" },
  "sa.teacher2": { en: "Teacher", ar: "المعلم" },
  "sa.revenue2": { en: "Revenue", ar: "الإيرادات" },
  "sa.status": { en: "Status", ar: "الحالة" },
  "sa.joinedAt": { en: "Joined", ar: "تاريخ الانضمام" },
  "sa.role": { en: "Role", ar: "الدور" },
  "sa.date": { en: "Date", ar: "التاريخ" },
  "sa.active": { en: "Active", ar: "نشط" },
  "sa.suspended": { en: "Suspended", ar: "موقوف" },
  "sa.pending2": { en: "Pending", ar: "معلق" },
  "sa.allAcademies": { en: "All Academies", ar: "جميع الأكاديميات" },
  "sa.platformOverview": { en: "Platform Overview", ar: "نظرة عامة على المنصة" },
  "sa.platformSubtitle": { en: "CLASSZ platform health and key metrics", ar: "صحة منصة CLASSZ والمقاييس الرئيسية" },

  // Support Center
  "sup.tickets": { en: "Tickets", ar: "التذاكر" },
  "sup.conversations": { en: "Conversations", ar: "المحادثات" },
  "sup.reports": { en: "Reports", ar: "التقارير" },
  "sup.faq": { en: "FAQ", ar: "الأسئلة الشائعة" },
  "sup.ticketsSubtitle": { en: "Manage support tickets", ar: "إدارة تذاكر الدعم" },
  "sup.conversationsSubtitle": { en: "Chat with users", ar: "الدردشة مع المستخدمين" },
  "sup.reportsSubtitle": { en: "User-filed reports", ar: "التقارير المقدمة" },
  "sup.faqSubtitle": { en: "Knowledge base articles", ar: "مقالات قاعدة المعرفة" },
  "sup.ticketId": { en: "Ticket ID", ar: "رقم التذكرة" },
  "sup.user": { en: "User", ar: "المستخدم" },
  "sup.category": { en: "Category", ar: "الفئة" },
  "sup.priority": { en: "Priority", ar: "الأولوية" },
  "sup.assignedTo": { en: "Assigned To", ar: "معيّن لـ" },
  "sup.status": { en: "Status", ar: "الحالة" },
  "sup.subject": { en: "Subject", ar: "الموضوع" },
  "sup.open": { en: "Open", ar: "مفتوح" },
  "sup.inProgress": { en: "In Progress", ar: "قيد المعالجة" },
  "sup.closed": { en: "Closed", ar: "مغلق" },
  "sup.technical": { en: "Technical", ar: "تقني" },
  "sup.payment": { en: "Payment", ar: "دفع" },
  "sup.academic": { en: "Academic", ar: "أكاديمي" },
  "sup.low": { en: "Low", ar: "منخفض" },
  "sup.medium": { en: "Medium", ar: "متوسط" },
  "sup.high": { en: "High", ar: "عالي" },
  "sup.urgent": { en: "Urgent", ar: "عاجل" },
  "sup.assign": { en: "Assign", ar: "تعيين" },
  "sup.reply": { en: "Reply", ar: "رد" },
  "sup.close": { en: "Close Ticket", ar: "إغلاق التذكرة" },
  "sup.all": { en: "All", ar: "الكل" },
  "sup.search": { en: "Search...", ar: "بحث..." },
  "sup.noResults": { en: "No results found.", ar: "لم يتم العثور على نتائج." },
  "sup.unread": { en: "unread", ar: "غير مقروءة" },
  "sup.type": { en: "Type", ar: "النوع" },
  "sup.reporter": { en: "Reporter", ar: "المُبلّغ" },
  "sup.bug": { en: "Bug", ar: "خطأ" },
  "sup.abuse": { en: "Abuse", ar: "إساءة" },
  "sup.content": { en: "Content", ar: "محتوى" },
  "sup.investigating": { en: "Investigating", ar: "قيد التحقيق" },
  "sup.resolved": { en: "Resolved", ar: "تم الحل" },
  "sup.views": { en: "Views", ar: "مشاهدات" },

  // Global Settings
  "gs.general": { en: "General", ar: "عام" },
  "gs.localization": { en: "Localization", ar: "التوطين" },
  "gs.payments": { en: "Payments", ar: "المدفوعات" },
  "gs.communication": { en: "Communication", ar: "التواصل" },
  "gs.security2": { en: "Security", ar: "الأمان" },
  "gs.featureToggles": { en: "Feature Toggles", ar: "تبديل الميزات" },
  "gs.platformName": { en: "Platform Name", ar: "اسم المنصة" },
  "gs.logo": { en: "Logo", ar: "الشعار" },
  "gs.colors": { en: "Colors", ar: "الألوان" },
  "gs.settingsTitle": { en: "Platform Settings", ar: "إعدادات المنصة" },
  "gs.settingsSubtitle": { en: "Configure platform-wide settings", ar: "تكوين إعدادات المنصة" },
  "gs.passwordPolicy": { en: "Password Policy", ar: "سياسة كلمة المرور" },
  "gs.sessionTimeout": { en: "Session Timeout", ar: "مهلة الجلسة" },
  "gs.parentPortal": { en: "Parent Portal", ar: "بوابة أولياء الأمور" },
  "gs.aiAssistant": { en: "AI Assistant", ar: "المساعد الذكي" },
  "gs.leaderboard": { en: "Leaderboard", ar: "لوحة الصدارة" },
  "gs.certificates": { en: "Certificates", ar: "الشهادات" },
  "gs.competitionSystem": { en: "Competition System", ar: "نظام المسابقات" },
  "gs.studentMemory": { en: "Student Memory", ar: "ذاكرة الطالب" },
  "gs.notifications": { en: "Notifications", ar: "الإشعارات" },
  "gs.enabled": { en: "Enabled", ar: "مفعّل" },
  "gs.disabled": { en: "Disabled", ar: "معطّل" },
  "gs.save": { en: "Save Changes", ar: "حفظ التغييرات" },

  // Admin Users
  "au.title": { en: "Admin Users", ar: "مستخدمو الإدارة" },
  "au.subtitle": { en: "Manage platform administrators", ar: "إدارة مسؤولي المنصة" },
  "au.name": { en: "Name", ar: "الاسم" },
  "au.email": { en: "Email", ar: "البريد الإلكتروني" },
  "au.role": { en: "Role", ar: "الدور" },
  "au.lastLogin": { en: "Last Login", ar: "آخر دخول" },
  "au.status": { en: "Status", ar: "الحالة" },
  "au.twoFactor": { en: "2FA", ar: "المصادقة الثنائية" },

  // Audit Logs (system)
  "sal.title": { en: "Audit Logs", ar: "سجل المراجعة" },
  "sal.subtitle": { en: "System-wide action log", ar: "سجل إجراءات النظام" },
  "sal.action": { en: "Action", ar: "الإجراء" },
  "sal.admin": { en: "Admin", ar: "المسؤول" },
  "sal.target": { en: "Target", ar: "الهدف" },
  "sal.details": { en: "Details", ar: "التفاصيل" },
  "sal.date": { en: "Date", ar: "التاريخ" },
  "sal.ip": { en: "IP", ar: "عنوان IP" },

  // Assistant Teacher
  "at.roleName": { en: "Assistant Teacher", ar: "معلم مساعد" },
  "at.roleTagline": { en: "Support & grade", ar: "دعم وتقييم" },
  "at.main": { en: "Main", ar: "الرئيسية" },
  "at.work": { en: "Workflow", ar: "سير العمل" },
  "at.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "at.dashboardSubtitle": { en: "Your assistant overview", ar: "نظرة عامة على المساعد" },
  "at.studentPods": { en: "Student Pods", ar: "مجموعات الطلاب" },
  "at.studentPodsSubtitle": { en: "Manage assigned student groups", ar: "إدارة مجموعات الطلاب المعينة" },
  "at.gradingQueue": { en: "Grading Queue", ar: "قائمة التصحيح" },
  "at.gradingQueueSubtitle": { en: "Submissions awaiting review", ar: "التسليمات بانتظار المراجعة" },
  "at.messages": { en: "Messages", ar: "الرسائل" },
  "at.messagesSubtitle": { en: "Student and parent messages", ar: "رسائل الطلاب وأولياء الأمور" },
  "at.followUp": { en: "Follow-up", ar: "المتابعة" },
  "at.followUpSubtitle": { en: "Students needing attention", ar: "طلاب بحاجة إلى متابعة" },
  "at.tasks": { en: "Tasks", ar: "المهام" },
  "at.tasksSubtitle": { en: "Task board", ar: "لوحة المهام" },
  "at.notes": { en: "Notes", ar: "الملاحظات" },
  "at.notesSubtitle": { en: "Private observations", ar: "ملاحظات خاصة" },
  "at.schedule": { en: "Schedule", ar: "الجدول" },
  "at.scheduleSubtitle": { en: "Daily plan", ar: "الخطة اليومية" },
  "at.performance": { en: "Performance", ar: "الأداء" },
  "at.performanceSubtitle": { en: "Your metrics", ar: "مقاييس أدائك" },
  "at.assignedStudents": { en: "Assigned Students", ar: "الطلاب المعينون" },
  "at.pendingGrading": { en: "Pending Grading", ar: "تصحيح معلق" },
  "at.unreadMessages": { en: "Unread Messages", ar: "رسائل غير مقروءة" },
  "at.tasksDue": { en: "Tasks Due", ar: "مهام مستحقة" },
  "at.atRiskStudents": { en: "At-Risk Students", ar: "طلاب في خطر" },
  "at.student": { en: "Student", ar: "الطالب" },
  "at.pod": { en: "Pod", ar: "المجموعة" },
  "at.grade": { en: "Grade", ar: "الصف" },
  "at.risk": { en: "Risk", ar: "الخطر" },
  "at.completion": { en: "Completion", ar: "الإكمال" },
  "at.pendingHW": { en: "Pending HW", ar: "واجبات معلقة" },
  "at.type": { en: "Type", ar: "النوع" },
  "at.course": { en: "Course", ar: "الدورة" },
  "at.assessment": { en: "Assessment", ar: "التقييم" },
  "at.priority": { en: "Priority", ar: "الأولوية" },
  "at.status": { en: "Status", ar: "الحالة" },
  "at.from": { en: "From", ar: "من" },
  "at.reason": { en: "Reason", ar: "السبب" },
  "at.category": { en: "Category", ar: "الفئة" },
  "at.severity": { en: "Severity", ar: "الشدة" },
  "at.lastContact": { en: "Last Contact", ar: "آخر تواصل" },
  "at.title2": { en: "Title", ar: "العنوان" },
  "at.dueDate": { en: "Due Date", ar: "تاريخ الاستحقاق" },
  "at.assignedBy": { en: "Assigned By", ar: "معيّن من" },
  "at.time": { en: "Time", ar: "الوقت" },
  "at.duration": { en: "Duration", ar: "المدة" },
  "at.gradedSubmissions": { en: "Graded Submissions", ar: "تسليمات مصححة" },
  "at.responseTime": { en: "Avg Response Time", ar: "متوسط وقت الاستجابة" },
  "at.studentSatisfaction": { en: "Student Satisfaction", ar: "رضا الطلاب" },
  "at.completedTasks": { en: "Completed Tasks", ar: "مهام مكتملة" },
  "at.weak": { en: "Weak Students", ar: "طلاب ضعاف" },
  "at.missingHw": { en: "Missing Homework", ar: "واجبات مفقودة" },
  "at.absent": { en: "Absent Students", ar: "طلاب غائبون" },
  "at.todo": { en: "To Do", ar: "قيد الانتظار" },
  "at.inProgress": { en: "In Progress", ar: "قيد التنفيذ" },
  "at.review": { en: "Review", ar: "مراجعة" },
  "at.done": { en: "Done", ar: "تم" },
  "at.grading": { en: "Grading", ar: "تصحيح" },
  "at.session": { en: "Session", ar: "حصة" },
  "at.meeting": { en: "Meeting", ar: "اجتماع" },
  "at.followUp2": { en: "Follow-up", ar: "متابعة" },
  "at.private": { en: "Private", ar: "خاص" },
  "at.shared": { en: "Shared", ar: "مشترك" },
  "at.search": { en: "Search...", ar: "بحث..." },

  // Content Manager
  "cm.roleName": { en: "Content Manager", ar: "مدير المحتوى" },
  "cm.roleTagline": { en: "Curate & publish", ar: "تنسيق ونشر" },
  "cm.content": { en: "Content", ar: "المحتوى" },
  "cm.manage": { en: "Manage", ar: "إدارة" },
  "cm.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "cm.dashboardSubtitle": { en: "Content management overview", ar: "نظرة عامة على إدارة المحتوى" },
  "cm.questionReview": { en: "Question Review", ar: "مراجعة الأسئلة" },
  "cm.questionReviewSubtitle": { en: "Approve or reject questions", ar: "الموافقة على الأسئلة أو رفضها" },
  "cm.importJobs": { en: "Import Jobs", ar: "مهام الاستيراد" },
  "cm.importJobsSubtitle": { en: "Import history and status", ar: "سجل الاستيراد والحالة" },
  "cm.mediaLibrary": { en: "Media Library", ar: "مكتبة الوسائط" },
  "cm.mediaLibrarySubtitle": { en: "PDFs, images, and videos", ar: "ملفات PDF والصور والفيديو" },
  "cm.tagsConcepts": { en: "Tags & Concepts", ar: "التصنيفات والمفاهيم" },
  "cm.tagsConceptsSubtitle": { en: "Manage taxonomy", ar: "إدارة التصنيف" },
  "cm.publishingQueue": { en: "Publishing Queue", ar: "قائمة النشر" },
  "cm.publishingQueueSubtitle": { en: "Pending publishing requests", ar: "طلبات النشر المعلقة" },
  "cm.reports": { en: "Reports", ar: "التقارير" },
  "cm.reportsSubtitle": { en: "Content statistics", ar: "إحصائيات المحتوى" },
  "cm.pendingQuestions": { en: "Pending Questions", ar: "أسئلة معلقة" },
  "cm.importJobsCount": { en: "Import Jobs", ar: "مهام الاستيراد" },
  "cm.mediaFiles": { en: "Media Files", ar: "ملفات الوسائط" },
  "cm.publishingRequests": { en: "Publishing Requests", ar: "طلبات النشر" },
  "cm.rejectedContent": { en: "Rejected Content", ar: "محتوى مرفوض" },
  "cm.question": { en: "Question", ar: "السؤال" },
  "cm.subject": { en: "Subject", ar: "المادة" },
  "cm.topic": { en: "Topic", ar: "الموضوع" },
  "cm.submittedBy": { en: "Submitted By", ar: "مقدم من" },
  "cm.type": { en: "Type", ar: "النوع" },
  "cm.difficulty": { en: "Difficulty", ar: "الصعوبة" },
  "cm.status": { en: "Status", ar: "الحالة" },
  "cm.pending": { en: "Pending", ar: "معلق" },
  "cm.approved": { en: "Approved", ar: "موافق عليه" },
  "cm.rejected": { en: "Rejected", ar: "مرفوض" },
  "cm.published": { en: "Published", ar: "منشور" },
  "cm.approve": { en: "Approve", ar: "موافقة" },
  "cm.reject": { en: "Reject", ar: "رفض" },
  "cm.search": { en: "Search...", ar: "بحث..." },
  "cm.all": { en: "All", ar: "الكل" },
  "cm.noResults": { en: "No results found.", ar: "لم يتم العثور على نتائج." },
  "cm.fileName": { en: "File Name", ar: "اسم الملف" },
  "cm.records": { en: "Records", ar: "السجلات" },
  "cm.errors": { en: "Errors", ar: "الأخطاء" },
  "cm.completed": { en: "Completed", ar: "مكتمل" },
  "cm.processing": { en: "Processing", ar: "قيد المعالجة" },
  "cm.failed": { en: "Failed", ar: "فشل" },
  "cm.queued": { en: "Queued", ar: "في الانتظار" },
  "cm.name": { en: "Name", ar: "الاسم" },
  "cm.size": { en: "Size", ar: "الحجم" },
  "cm.downloads": { en: "Downloads", ar: "التحميلات" },
  "cm.concept": { en: "Concept", ar: "مفهوم" },
  "cm.atomicConcept": { en: "Atomic Concept", ar: "مفهوم ذري" },
  "cm.tag": { en: "Tag", ar: "تصنيف" },
  "cm.usageCount": { en: "Usage", ar: "الاستخدام" },
  "cm.deprecated": { en: "Deprecated", ar: "مهمل" },
  "cm.active": { en: "Active", ar: "نشط" },
  "cm.title": { en: "Title", ar: "العنوان" },
  "cm.academy": { en: "Academy", ar: "الأكاديمية" },
  "cm.pdfs": { en: "PDFs", ar: "ملفات PDF" },
  "cm.images": { en: "Images", ar: "صور" },
  "cm.videos": { en: "Videos", ar: "فيديو" },

  // Settings page
  "sa.settingsSubtitle": { en: "Configure platform-wide settings", ar: "تكوين إعدادات المنصة" },
  "set.general": { en: "General", ar: "عام" },
  "set.localization": { en: "Localization", ar: "التوطين" },
  "set.payments": { en: "Payments", ar: "المدفوعات" },
  "set.communication": { en: "Communication", ar: "التواصل" },
  "set.security": { en: "Security", ar: "الأمان" },
  "set.features": { en: "Features", ar: "الميزات" },
  "set.generalSettings": { en: "General Settings", ar: "الإعدادات العامة" },
  "set.platformName": { en: "Platform Name", ar: "اسم المنصة" },
  "set.logo": { en: "Logo", ar: "الشعار" },
  "set.upload": { en: "Upload", ar: "رفع" },
  "set.primaryColor": { en: "Primary Color", ar: "اللون الأساسي" },
  "set.localizationSettings": { en: "Localization Settings", ar: "إعدادات التوطين" },
  "set.language": { en: "Language", ar: "اللغة" },
  "set.arabic": { en: "Arabic", ar: "العربية" },
  "set.english": { en: "English", ar: "الإنجليزية" },
  "set.rtlLayout": { en: "RTL Layout", ar: "تخطيط من اليمين لليسار" },
  "set.rtlDescription": { en: "Enable right-to-left layout for Arabic", ar: "تفعيل التخطيط من اليمين لليسار للعربية" },
  "set.paymentGateways": { en: "Payment Gateways", ar: "بوابات الدفع" },
  "set.vodafoneCashDesc": { en: "Accept Vodafone Cash payments", ar: "قبول مدفوعات فودافون كاش" },
  "set.instaPayDesc": { en: "Accept InstaPay transfers", ar: "قبول تحويلات إنستاباي" },
  "set.stripeDesc": { en: "Accept international card payments", ar: "قبول المدفوعات الدولية بالبطاقة" },
  "set.bankTransferDesc": { en: "Accept bank wire transfers", ar: "قبول التحويلات البنكية" },
  "set.communicationChannels": { en: "Communication Channels", ar: "قنوات التواصل" },
  "set.whatsappDesc": { en: "Send notifications via WhatsApp", ar: "إرسال إشعارات عبر واتساب" },
  "set.emailDesc": { en: "Send notifications via email", ar: "إرسال إشعارات عبر البريد" },
  "set.securitySettings": { en: "Security Settings", ar: "إعدادات الأمان" },
  "set.minPasswordLength": { en: "Minimum Password Length", ar: "الحد الأدنى لطول كلمة المرور" },
  "set.minPasswordDesc": { en: "Minimum characters required for passwords", ar: "الحد الأدنى من الأحرف المطلوبة لكلمات المرور" },
  "set.sessionTimeout": { en: "Session Timeout", ar: "مهلة الجلسة" },
  "set.sessionTimeoutDesc": { en: "Auto-logout after inactivity", ar: "تسجيل خروج تلقائي بعد عدم النشاط" },
  "set.minutes": { en: "minutes", ar: "دقائق" },
  "set.featureToggles": { en: "Feature Toggles", ar: "تبديل الميزات" },
  "set.saveChanges": { en: "Save Changes", ar: "حفظ التغييرات" },

  // Assistant Teacher extras
  "at.absentStudents": { en: "Absent Students", ar: "طلاب غائبون" },
  "at.actions": { en: "Actions", ar: "الإجراءات" },
  "at.addNote": { en: "Add Note", ar: "إضافة ملاحظة" },
  "at.alerts": { en: "Alerts", ar: "تنبيهات" },
  "at.all": { en: "All", ar: "الكل" },
  "at.allStatuses": { en: "All Statuses", ar: "كل الحالات" },
  "at.allTime": { en: "All Time", ar: "كل الوقت" },
  "at.allTypes": { en: "All Types", ar: "كل الأنواع" },
  "at.atRisk": { en: "At Risk", ar: "في خطر" },
  "at.average": { en: "Average", ar: "المتوسط" },
  "at.avgCompletion": { en: "Avg Completion", ar: "متوسط الإكمال" },
  "at.avgResponseTime": { en: "Avg Response Time", ar: "متوسط وقت الاستجابة" },
  "at.cancel": { en: "Cancel", ar: "إلغاء" },
  "at.completed": { en: "Completed", ar: "مكتمل" },
  "at.confirm": { en: "Confirm", ar: "تأكيد" },
  "at.contactParent": { en: "Contact Parent", ar: "تواصل مع ولي الأمر" },
  "at.contactParentDesc": { en: "Send notification to student's parent", ar: "إرسال إشعار لولي أمر الطالب" },
  "at.content": { en: "Content", ar: "المحتوى" },
  "at.createPlan": { en: "Create Plan", ar: "إنشاء خطة" },
  "at.createPlanDesc": { en: "Create a revision plan for this student", ar: "إنشاء خطة مراجعة لهذا الطالب" },
  "at.essay": { en: "Essay", ar: "مقال" },
  "at.feedback": { en: "Feedback", ar: "ملاحظات" },
  "at.feedbackPlaceholder": { en: "Enter feedback...", ar: "أدخل الملاحظات..." },
  "at.file": { en: "File", ar: "ملف" },
  "at.followUpAlerts": { en: "Follow-up Alerts", ar: "تنبيهات المتابعة" },
  "at.fromParents": { en: "From Parents", ar: "من أولياء الأمور" },
  "at.fromStudents": { en: "From Students", ar: "من الطلاب" },
  "at.gradeSubmission": { en: "Grade Submission", ar: "تصحيح التسليم" },
  "at.graded": { en: "Graded", ar: "مصحح" },
  "at.gradedThisWeek": { en: "Graded This Week", ar: "مصحح هذا الأسبوع" },
  "at.gradingSessions": { en: "Grading Sessions", ar: "جلسات التصحيح" },
  "at.highSeverity": { en: "High Severity", ar: "شدة عالية" },
  "at.homework": { en: "Homework", ar: "واجب" },
  "at.lastActive": { en: "Last Active", ar: "آخر نشاط" },
  "at.mediumSeverity": { en: "Medium Severity", ar: "شدة متوسطة" },
  "at.missingHomework": { en: "Missing Homework", ar: "واجبات مفقودة" },
  "at.name": { en: "Name", ar: "الاسم" },
  "at.noFollowUps": { en: "No follow-ups found.", ar: "لم يتم العثور على متابعات." },
  "at.noItemsFound": { en: "No items found.", ar: "لم يتم العثور على عناصر." },
  "at.noMessages": { en: "No messages.", ar: "لا توجد رسائل." },
  "at.noNotesFound": { en: "No notes found.", ar: "لم يتم العثور على ملاحظات." },
  "at.noStudentsFound": { en: "No students found.", ar: "لم يتم العثور على طلاب." },
  "at.noTasks": { en: "No tasks.", ar: "لا توجد مهام." },
  "at.noteContentPlaceholder": { en: "Write your note...", ar: "اكتب ملاحظتك..." },
  "at.parents": { en: "Parents", ar: "أولياء الأمور" },
  "at.pending2": { en: "Pending", ar: "معلق" },
  "at.pending": { en: "Pending", ar: "معلق" },
  "at.podOverview": { en: "Pod Overview", ar: "نظرة عامة على المجموعات" },
  "at.privateNote": { en: "Private Note", ar: "ملاحظة خاصة" },
  "at.privateNoteDesc": { en: "Only visible to you", ar: "مرئية لك فقط" },
  "at.quiz": { en: "Quiz", ar: "اختبار" },
  "at.resolved": { en: "Resolved", ar: "تم الحل" },
  "at.responseRate": { en: "Response Rate", ar: "معدل الاستجابة" },
  "at.responseRateDesc": { en: "Messages responded within 24h", ar: "الرسائل المرد عليها خلال 24 ساعة" },
  "at.results": { en: "Results", ar: "النتائج" },
  "at.returned": { en: "Returned", ar: "مُعاد" },
  "at.riskLevel": { en: "Risk Level", ar: "مستوى الخطر" },
  "at.satisfactionDesc": { en: "Based on student ratings", ar: "بناءً على تقييمات الطلاب" },
  "at.saveGrade": { en: "Save Grade", ar: "حفظ الدرجة" },
  "at.saveNote": { en: "Save Note", ar: "حفظ الملاحظة" },
  "at.score": { en: "Score", ar: "الدرجة" },
  "at.searchByStudent": { en: "Search by student...", ar: "بحث حسب الطالب..." },
  "at.searchNotes": { en: "Search notes...", ar: "بحث في الملاحظات..." },
  "at.searchStudents": { en: "Search students...", ar: "بحث عن طلاب..." },
  "at.selectStudent": { en: "Select student", ar: "اختر طالب" },
  "at.send": { en: "Send", ar: "إرسال" },
  "at.sendReminder": { en: "Send Reminder", ar: "إرسال تذكير" },
  "at.sendReminderDesc": { en: "Send reminder to student", ar: "إرسال تذكير للطالب" },
  "at.sessions2": { en: "Sessions", ar: "الحصص" },
  "at.slots": { en: "Slots", ar: "الفترات" },
  "at.students": { en: "Students", ar: "الطلاب" },
  "at.submitted": { en: "Submitted", ar: "مُسلَّم" },
  "at.teachers": { en: "Teachers", ar: "المعلمون" },
  "at.thisWeek": { en: "This Week", ar: "هذا الأسبوع" },
  "at.todaysSchedule": { en: "Today's Schedule", ar: "جدول اليوم" },
  "at.total": { en: "Total", ar: "الإجمالي" },
  "at.totalFollowUps": { en: "Total Follow-ups", ar: "إجمالي المتابعات" },
  "at.totalHours": { en: "Total Hours", ar: "إجمالي الساعات" },
  "at.totalMessages": { en: "Total Messages", ar: "إجمالي الرسائل" },
  "at.totalNotes": { en: "Total Notes", ar: "إجمالي الملاحظات" },
  "at.totalSlots": { en: "Total Slots", ar: "إجمالي الفترات" },
  "at.totalTasks": { en: "Total Tasks", ar: "إجمالي المهام" },
  "at.typeReply": { en: "Type your reply...", ar: "اكتب ردك..." },
  "at.unread": { en: "Unread", ar: "غير مقروء" },
  "at.viewAll": { en: "View All", ar: "عرض الكل" },
  "at.weakStudents": { en: "Weak Students", ar: "طلاب ضعاف" },
  "at.weeklyGradingOutput": { en: "Weekly Grading Output", ar: "ناتج التصحيح الأسبوعي" },
  "at.yourReply": { en: "Your Reply", ar: "ردك" },
  "at.createPod": { en: "Create Pod", ar: "إنشاء مجموعة" },
  "at.noPodAccess": { en: "No teacher has granted you pod access yet.", ar: "لم يمنحك أي معلم صلاحية الوصول للمجموعات بعد." },
  "at.selectCourse": { en: "Select course", ar: "اختر الدورة" },
  "at.noPodsYet": { en: "No pods created for this course yet.", ar: "لم يتم إنشاء أي مجموعات لهذه الدورة بعد." },
  "at.members": { en: "Members", ar: "الأعضاء" },
  "at.editPod": { en: "Edit Pod", ar: "تعديل المجموعة" },
  "at.podName": { en: "Pod name", ar: "اسم المجموعة" },
  "at.podDescription": { en: "Description", ar: "الوصف" },
  "at.save": { en: "Save", ar: "حفظ" },
  "at.deletePod": { en: "Delete Pod", ar: "حذف المجموعة" },
  "at.deletePodConfirm": { en: "Are you sure you want to delete \"{name}\"? This cannot be undone.", ar: "هل أنت متأكد من حذف \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء." },
  "at.delete": { en: "Delete", ar: "حذف" },
  "at.noMembersYet": { en: "No members in this pod yet.", ar: "لا يوجد أعضاء في هذه المجموعة بعد." },
  "at.addMember": { en: "Add member", ar: "إضافة عضو" },
  "at.noStudentsToAdd": { en: "No more students to add.", ar: "لا يوجد طلاب إضافيون لإضافتهم." },
  "at.close": { en: "Close", ar: "إغلاق" },
  "at.maxScore": { en: "Max score", ar: "الدرجة القصوى" },
  "at.noStudentsDataAccess": { en: "No teacher has granted you student-data access yet.", ar: "لم يمنحك أي معلم صلاحية الوصول لبيانات الطلاب بعد." },
  "at.low": { en: "Low", ar: "منخفض" },
  "at.totalStudents": { en: "Total Students", ar: "إجمالي الطلاب" },
  "at.avgQuizScore": { en: "Avg Quiz Score", ar: "متوسط درجة الاختبار" },
  "at.certificatesIssued": { en: "Certificates Issued", ar: "الشهادات الصادرة" },
  "at.studentProgress": { en: "Student Progress", ar: "تقدم الطلاب" },
  "at.noAccessYet": { en: "No teacher has granted you access to any module yet.", ar: "لم يمنحك أي معلم صلاحية الوصول لأي وحدة بعد." },
  "at.viewInvitations": { en: "View invitations", ar: "عرض الدعوات" },
  "at.futureModuleTitle": { en: "Coming soon", ar: "قريباً" },
  "at.futureModuleDesc": { en: "This module isn't available yet in this release. It'll appear here once it's built.", ar: "هذه الوحدة غير متاحة بعد في هذا الإصدار. ستظهر هنا بمجرد بنائها." },
  "common.loading": { en: "Loading...", ar: "جارٍ التحميل..." },

  // Content Manager extras
  "cm.actions": { en: "Actions", ar: "الإجراءات" },
  "cm.add": { en: "Add", ar: "إضافة" },
  "cm.addTagConcept": { en: "Add Tag/Concept", ar: "إضافة تصنيف/مفهوم" },
  "cm.allDifficulties": { en: "All Difficulties", ar: "كل الصعوبات" },
  "cm.allImportJobs": { en: "All Import Jobs", ar: "كل مهام الاستيراد" },
  "cm.allStatuses": { en: "All Statuses", ar: "كل الحالات" },
  "cm.allTypes": { en: "All Types", ar: "كل الأنواع" },
  "cm.atomicConcepts": { en: "Atomic Concepts", ar: "مفاهيم ذرية" },
  "cm.by": { en: "by", ar: "بواسطة" },
  "cm.cancel": { en: "Cancel", ar: "إلغاء" },
  "cm.concepts": { en: "Concepts", ar: "مفاهيم" },
  "cm.confirmApprove": { en: "Confirm Approve", ar: "تأكيد الموافقة" },
  "cm.confirmApproveMessage": { en: "Are you sure you want to approve this?", ar: "هل أنت متأكد من الموافقة؟" },
  "cm.confirmReject": { en: "Confirm Reject", ar: "تأكيد الرفض" },
  "cm.confirmRejectMessage": { en: "Are you sure you want to reject this?", ar: "هل أنت متأكد من الرفض؟" },
  "cm.contentByType": { en: "Content by Type", ar: "المحتوى حسب النوع" },
  "cm.course": { en: "Course", ar: "الدورة" },
  "cm.date": { en: "Date", ar: "التاريخ" },
  "cm.easy": { en: "Easy", ar: "سهل" },
  "cm.enterName": { en: "Enter name", ar: "أدخل الاسم" },
  "cm.enterSubject": { en: "Enter subject", ar: "أدخل المادة" },
  "cm.files": { en: "Files", ar: "ملفات" },
  "cm.hard": { en: "Hard", ar: "صعب" },
  "cm.latestImportJobs": { en: "Latest Import Jobs", ar: "أحدث مهام الاستيراد" },
  "cm.lesson": { en: "Lesson", ar: "درس" },
  "cm.medium": { en: "Medium", ar: "متوسط" },
  "cm.monthlyImportTrend": { en: "Monthly Import Trend", ar: "اتجاه الاستيراد الشهري" },
  "cm.noRecentActivity": { en: "No recent activity", ar: "لا يوجد نشاط حديث" },
  "cm.questionBank": { en: "Question Bank", ar: "بنك الأسئلة" },
  "cm.questionDetail": { en: "Question Detail", ar: "تفاصيل السؤال" },
  "cm.questionsBySubject": { en: "Questions by Subject", ar: "الأسئلة حسب المادة" },
  "cm.quiz": { en: "Quiz", ar: "اختبار" },
  "cm.recentActivity": { en: "Recent Activity", ar: "النشاط الأخير" },
  "cm.recentQuestionReviews": { en: "Recent Question Reviews", ar: "أحدث مراجعات الأسئلة" },
  "cm.reviewedBy": { en: "Reviewed By", ar: "مراجعة بواسطة" },
  "cm.searchMedia": { en: "Search media...", ar: "بحث في الوسائط..." },
  "cm.searchQuestions": { en: "Search questions...", ar: "بحث في الأسئلة..." },
  "cm.searchTagsConcepts": { en: "Search tags & concepts...", ar: "بحث في التصنيفات والمفاهيم..." },
  "cm.tags": { en: "Tags", ar: "تصنيفات" },
  "cm.uploadedBy": { en: "Uploaded By", ar: "رفع بواسطة" },
  "cm.viewAll": { en: "View All", ar: "عرض الكل" },

  // SuperAdmin extras
  "sa.academy": { en: "Academy", ar: "الأكاديمية" },
  "sa.academyName": { en: "Academy Name", ar: "اسم الأكاديمية" },
  "sa.actions": { en: "Actions", ar: "الإجراءات" },
  "sa.activityTimeline": { en: "Activity Timeline", ar: "الجدول الزمني للنشاط" },
  "sa.allStatuses": { en: "All Statuses", ar: "كل الحالات" },
  "sa.noResults": { en: "No results found.", ar: "لم يتم العثور على نتائج." },
  "sa.of": { en: "of", ar: "من" },
  "sa.pending": { en: "Pending", ar: "معلق" },
  "sa.revenue": { en: "Revenue", ar: "الإيرادات" },
  "sa.searchAcademies": { en: "Search academies...", ar: "بحث عن أكاديميات..." },
  "sa.showing": { en: "Showing", ar: "عرض" },
  "sa.teacher": { en: "Teacher", ar: "المعلم" },
  "sa.totalAcademies": { en: "Total Academies", ar: "إجمالي الأكاديميات" },
  "sa.supportCenter": { en: "Support Center", ar: "مركز الدعم" },
  "sa.supportSubtitle": { en: "Manage support operations", ar: "إدارة عمليات الدعم" },
  "sa.supportCenterSubtitle": { en: "Manage support operations", ar: "إدارة عمليات الدعم" },

  // Support extras
  "sup.allCategories": { en: "All Categories", ar: "كل الفئات" },
  "sup.allPriorities": { en: "All Priorities", ar: "كل الأولويات" },
  "sup.allStatuses": { en: "All Statuses", ar: "كل الحالات" },
  "sup.allTypes": { en: "All Types", ar: "كل الأنواع" },
  "sup.categories": { en: "Categories", ar: "الفئات" },
  "sup.created": { en: "Created", ar: "تم الإنشاء" },
  "sup.date": { en: "Date", ar: "التاريخ" },
  "sup.description": { en: "Description", ar: "الوصف" },
  "sup.lastReply": { en: "Last Reply", ar: "آخر رد" },
  "sup.noConversations": { en: "No conversations.", ar: "لا توجد محادثات." },
  "sup.noFaq": { en: "No FAQ found.", ar: "لم يتم العثور على أسئلة." },
  "sup.noReports": { en: "No reports found.", ar: "لم يتم العثور على تقارير." },
  "sup.noTickets": { en: "No tickets found.", ar: "لم يتم العثور على تذاكر." },
  "sup.openReports": { en: "Open Reports", ar: "تقارير مفتوحة" },
  "sup.parents": { en: "Parents", ar: "أولياء الأمور" },
  "sup.searchFaq": { en: "Search FAQ...", ar: "بحث في الأسئلة الشائعة..." },
  "sup.searchReports": { en: "Search reports...", ar: "بحث في التقارير..." },
  "sup.searchTickets": { en: "Search tickets...", ar: "بحث في التذاكر..." },
  "sup.studentConvs": { en: "Student Conversations", ar: "محادثات الطلاب" },
  "sup.students": { en: "Students", ar: "الطلاب" },
  "sup.submittedBy": { en: "Submitted By", ar: "مقدم من" },
  "sup.teacherConvs": { en: "Teacher Conversations", ar: "محادثات المعلمين" },
  "sup.teachers": { en: "Teachers", ar: "المعلمون" },
  "sup.totalConversations": { en: "Total Conversations", ar: "إجمالي المحادثات" },
  "sup.totalFaq": { en: "Total FAQ", ar: "إجمالي الأسئلة الشائعة" },
  "sup.totalViews": { en: "Total Views", ar: "إجمالي المشاهدات" },
  "sup.typeReply": { en: "Type your reply...", ar: "اكتب ردك..." },
  "sup.unreadMessages": { en: "Unread Messages", ar: "رسائل غير مقروءة" },
};

const translate = (key: string, lang: Lang, params?: Record<string, string | number>) => {
  const direct = dict[key]?.[lang];
  const resolved = direct ?? Object.values(dict).find((entry) => entry.en === key)?.[lang] ?? key;
  if (!params) return resolved;
  return Object.entries(params).reduce(
    (text, [paramKey, paramValue]) => text.replaceAll(`{${paramKey}}`, String(paramValue)),
    resolved,
  );
};

const getStoredTheme = (): Theme => {
  if (typeof window === "undefined") return "dark";
  const stored = window.localStorage.getItem("classz-theme");
  return stored === "light" || stored === "dark" || stored === "game" ? stored : "dark";
};

const getStoredLang = (): Lang => {
  if (typeof window === "undefined") return "en";
  const stored = window.localStorage.getItem("classz-lang");
  return stored === "ar" || stored === "en" ? stored : "en";
};

const getStoredUiSoundsEnabled = (): boolean => {
  if (typeof window === "undefined") return true;
  const stored = window.localStorage.getItem("classz-ui-sounds");
  return stored === null ? true : stored === "true";
};

const getStoredCinematicLoginMotionEnabled = (): boolean => {
  if (typeof window === "undefined") return true;
  const stored = window.localStorage.getItem("classz-cinematic-login-motion");
  return stored === null ? true : stored === "true";
};

export function AppProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>(getStoredTheme);
  const [lang, setLangState] = useState<Lang>(getStoredLang);
  const [uiSoundsEnabled, setUiSoundsEnabledState] = useState<boolean>(getStoredUiSoundsEnabled);
  const [cinematicLoginMotionEnabled, setCinematicLoginMotionEnabledState] = useState<boolean>(
    getStoredCinematicLoginMotionEnabled,
  );

  useEffect(() => {
    const root = document.documentElement;
    root.classList.toggle("dark", theme !== "light");
    root.classList.toggle("game", theme === "game");
    localStorage.setItem("classz-theme", theme);
  }, [theme]);

  useEffect(() => {
    const root = document.documentElement;
    const nextDir = lang === "ar" ? "rtl" : "ltr";
    root.setAttribute("dir", nextDir);
    root.setAttribute("lang", lang);
    root.dataset.lang = lang;
    root.dataset.dir = nextDir;
    document.body.setAttribute("dir", nextDir);
    document.body.setAttribute("lang", lang);
    localStorage.setItem("classz-lang", lang);
  }, [lang]);

  useEffect(() => {
    localStorage.setItem("classz-ui-sounds", String(uiSoundsEnabled));
  }, [uiSoundsEnabled]);

  useEffect(() => {
    localStorage.setItem("classz-cinematic-login-motion", String(cinematicLoginMotionEnabled));
  }, [cinematicLoginMotionEnabled]);

  useEffect(() => {
    const handleStorage = (event: StorageEvent) => {
      if (event.storageArea !== window.localStorage || !event.key) return;
      if (event.key === "classz-theme") {
        const nextTheme = event.newValue === "light" || event.newValue === "dark" || event.newValue === "game"
          ? event.newValue
          : "dark";
        setThemeState(nextTheme);
      }
      if (event.key === "classz-lang") {
        const nextLang = event.newValue === "ar" || event.newValue === "en" ? event.newValue : "en";
        setLangState(nextLang);
      }
      if (event.key === "classz-ui-sounds") {
        setUiSoundsEnabledState(event.newValue === null ? true : event.newValue === "true");
      }
      if (event.key === "classz-cinematic-login-motion") {
        setCinematicLoginMotionEnabledState(event.newValue === null ? true : event.newValue === "true");
      }
    };

    window.addEventListener("storage", handleStorage);
    return () => window.removeEventListener("storage", handleStorage);
  }, []);

  const value: AppState = {
    theme,
    setTheme: setThemeState,
    toggleTheme: () => setThemeState((p) => (p === "light" ? "dark" : p === "dark" ? "game" : "light")),
    uiSoundsEnabled,
    setUiSoundsEnabled: setUiSoundsEnabledState,
    toggleUiSounds: () => setUiSoundsEnabledState((current) => !current),
    cinematicLoginMotionEnabled,
    setCinematicLoginMotionEnabled: setCinematicLoginMotionEnabledState,
    toggleCinematicLoginMotion: () => setCinematicLoginMotionEnabledState((current) => !current),
    lang,
    setLang: setLangState,
    toggleLang: () => setLangState((p) => (p === "en" ? "ar" : "en")),
    dir: lang === "ar" ? "rtl" : "ltr",
    t: (key, params) => translate(key, lang, params),
  };

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error("useApp must be used within AppProvider");
  return ctx;
}
