export type NotifSender = "classz" | "teacher" | "assistant" | "parent" | "system";
export type NotifPriority = "normal" | "important" | "urgent";

export interface StudentNotification {
  id: string;
  sender: NotifSender;
  senderName: string;
  title: string;
  message: string;
  dateTime: string;
  course?: string;
  subject?: string;
  priority: NotifPriority;
  read: boolean;
  pinned: boolean;
  archived: boolean;
  replyAllowed: boolean;
  replySent: string | null;
  actionLabel?: string;
  actionRoute?: string;
}

export const senderConfig: Record<NotifSender, { label: string; color: string; bg: string }> = {
  classz:    { label: "CLASSZ",            color: "text-violet-400", bg: "bg-violet-500/15" },
  teacher:   { label: "Teacher",           color: "text-blue-400",   bg: "bg-blue-500/15" },
  assistant: { label: "Teacher Assistant",  color: "text-cyan-400",   bg: "bg-cyan-500/15" },
  parent:    { label: "Parent",            color: "text-rose-400",   bg: "bg-rose-500/15" },
  system:    { label: "System",            color: "text-amber-400",  bg: "bg-amber-500/15" },
};

export const priorityConfig: Record<NotifPriority, { label: string; color: string; border: string }> = {
  normal:    { label: "Normal",    color: "text-slate-400",   border: "border-white/10" },
  important: { label: "Important", color: "text-amber-400",   border: "border-amber-500/20" },
  urgent:    { label: "Urgent",    color: "text-red-400",     border: "border-red-500/25" },
};

export const initialNotifications: StudentNotification[] = [
  {
    id: "notif-1",
    sender: "teacher",
    senderName: "Dr. Ahmed Gharib",
    title: "New Session Opened: Organic Chemistry",
    message: "Session 3 — Aromatic Chemistry is now available. You have 5 days to complete all items. Start with the video on Benzene Structure.",
    dateTime: "2026-06-20T09:00:00Z",
    course: "Chemistry Grade 12",
    subject: "Chemistry",
    priority: "important",
    read: false,
    pinned: false,
    archived: false,
    replyAllowed: true,
    replySent: null,
    actionLabel: "Go to Session",
    actionRoute: "/student/courses/ec1/session",
  },
  {
    id: "notif-2",
    sender: "teacher",
    senderName: "Dr. Layla Hassan",
    title: "Homework Assigned: Differentiation",
    message: "Homework Quiz on Differentiation is now available in Session 2. Due date: June 22, 2026. You have 3 attempts allowed. Good luck!",
    dateTime: "2026-06-19T14:30:00Z",
    course: "Advanced Mathematics",
    subject: "Mathematics",
    priority: "urgent",
    read: false,
    pinned: true,
    archived: false,
    replyAllowed: false,
    replySent: null,
    actionLabel: "Open Homework",
    actionRoute: "/student/courses/ec1/session",
  },
  {
    id: "notif-3",
    sender: "assistant",
    senderName: "TA Sarah",
    title: "Answer to Your Question",
    message: "Regarding your question about the chain rule: The chain rule multiplies by the inner derivative because we are differentiating a composition of functions. Think of peeling layers — outer derivative times inner derivative. Let me know if you need a worked example.",
    dateTime: "2026-06-19T11:20:00Z",
    course: "Advanced Mathematics",
    subject: "Mathematics",
    priority: "normal",
    read: false,
    pinned: false,
    archived: false,
    replyAllowed: true,
    replySent: null,
  },
  {
    id: "notif-4",
    sender: "parent",
    senderName: "Mom",
    title: "Great Job This Week!",
    message: "I saw your quiz results — 88% on derivatives! Keep it up. Dad and I are proud of your consistency. Don't forget to take breaks too.",
    dateTime: "2026-06-19T08:00:00Z",
    priority: "normal",
    read: true,
    pinned: false,
    archived: false,
    replyAllowed: true,
    replySent: "Thank you Mom! I'll keep working hard.",
  },
  {
    id: "notif-5",
    sender: "classz",
    senderName: "CLASSZ Platform",
    title: "New Feature: Smart Notes",
    message: "We've launched Smart Notes! Your notes are now auto-detected as formulas, definitions, or questions. Check it out in My Session → Notes tab.",
    dateTime: "2026-06-18T16:00:00Z",
    priority: "normal",
    read: true,
    pinned: false,
    archived: false,
    replyAllowed: false,
    replySent: null,
  },
  {
    id: "notif-6",
    sender: "system",
    senderName: "System",
    title: "Payment Successful",
    message: "Your payment of $15 for Session 2: Differential Calculus has been processed successfully. 5-day access started on June 18, 2026.",
    dateTime: "2026-06-18T14:30:00Z",
    priority: "normal",
    read: true,
    pinned: false,
    archived: false,
    replyAllowed: false,
    replySent: null,
  },
  {
    id: "notif-7",
    sender: "teacher",
    senderName: "Mr. Omar Khalil",
    title: "Exam Reminder: Wave Motion Quiz",
    message: "Don't forget — the Wave Motion quiz is scheduled for tomorrow at 9:00 AM. Review your notes on Doppler Effect and wave properties. The quiz covers Sessions 1 and 2.",
    dateTime: "2026-06-18T10:00:00Z",
    course: "Physics Grade 12",
    subject: "Physics",
    priority: "urgent",
    read: true,
    pinned: false,
    archived: false,
    replyAllowed: true,
    replySent: "Thank you, I'll prepare tonight.",
  },
  {
    id: "notif-8",
    sender: "classz",
    senderName: "CLASSZ Platform",
    title: "Subscription Reminder",
    message: "Your CLASSZ Pro subscription renews on July 14, 2026. To manage your plan or update payment method, visit Settings → Subscription.",
    dateTime: "2026-06-17T12:00:00Z",
    priority: "normal",
    read: true,
    pinned: false,
    archived: false,
    replyAllowed: false,
    replySent: null,
  },
  {
    id: "notif-9",
    sender: "system",
    senderName: "System",
    title: "Certificate Issued: English Grade 12",
    message: "Congratulations! Your Certificate of Achievement for English Grade 12 has been issued. View and download it from the Certificates page.",
    dateTime: "2026-06-16T09:00:00Z",
    priority: "important",
    read: true,
    pinned: false,
    archived: false,
    replyAllowed: false,
    replySent: null,
    actionLabel: "View Certificate",
    actionRoute: "/student/certificates",
  },
  {
    id: "notif-10",
    sender: "assistant",
    senderName: "TA Mohamed",
    title: "Revision Reminder: Equilibrium",
    message: "Hi Aya, you haven't revised Chemical Equilibrium in 5 days. Your weak concept analysis shows Ksp Calculations at 55%. I recommend practicing at least 10 questions today.",
    dateTime: "2026-06-15T15:00:00Z",
    course: "Chemistry Grade 12",
    subject: "Chemistry",
    priority: "important",
    read: true,
    pinned: false,
    archived: false,
    replyAllowed: true,
    replySent: null,
  },
  {
    id: "notif-11",
    sender: "system",
    senderName: "System",
    title: "Login from New Device",
    message: "A new login was detected from Windows 11 device at 2:14 PM. If this was you, no action needed. If not, change your password immediately.",
    dateTime: "2026-06-14T14:14:00Z",
    priority: "urgent",
    read: true,
    pinned: false,
    archived: false,
    replyAllowed: false,
    replySent: null,
  },
  {
    id: "notif-12",
    sender: "parent",
    senderName: "Dad",
    title: "How's Physics Going?",
    message: "Your mom told me you're studying hard. How's the physics project coming along? Let me know if you need any help with the lab report.",
    dateTime: "2026-06-13T20:00:00Z",
    priority: "normal",
    read: true,
    pinned: false,
    archived: false,
    replyAllowed: true,
    replySent: "Going well! I'll finish the lab report this weekend.",
  },
];
